! This code is part of Qiskit.
!
! (C) Copyright IBM 2026.
!
! This code is licensed under the Apache License, Version 2.0. You may
! obtain a copy of this license in the LICENSE.txt file in the root directory
! of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
!
! Any modifications or derivative works of this code must retain this
! copyright notice, and modified files need to carry a notice indicating
! that they have been altered from the originals.

! =============================================================================
! qiskit_c_api.f90  —  generated by generate_bindings.py
!
! DO NOT EDIT — regenerate with:
!   python fortran-swig/generate_bindings.py
! =============================================================================

module qiskit_c_api
  use, intrinsic :: iso_c_binding, only : c_ptr, c_int, c_int32_t, c_size_t

  implicit none (type, external)
  private

  public :: QkExitCode_Success, QkExitCode_CInputError, QkExitCode_NullPointerError, QkExitCode_AlignmentError, &
      QkExitCode_IndexError, QkExitCode_DuplicateIndexError, QkExitCode_InvalidOperationKind, QkExitCode_ArithmeticError, &
      QkExitCode_MismatchedQubits, QkExitCode_ExpectedUnitary, QkExitCode_TargetError, QkExitCode_TargetInstAlreadyExists, &
      QkExitCode_TargetQargMismatch, QkExitCode_TargetInvalidQargsKey, QkExitCode_TargetInvalidInstKey, &
      QkExitCode_TranspilerError, QkExitCode_DagError, QkExitCode_DagComposeMismatch, QkExitCode_DagComposeMissingBit, &
      QkExitCode_ParameterError, QkExitCode_ParameterNameConflict, QkGate_GlobalPhase, QkGate_H, QkGate_I, QkGate_X, QkGate_Y, &
      QkGate_Z, QkGate_Phase, QkGate_R, QkGate_RX, QkGate_RY, QkGate_RZ, QkGate_S, QkGate_Sdg, QkGate_SX, QkGate_SXdg, QkGate_T, &
      QkGate_Tdg, QkGate_U, QkGate_U1, QkGate_U2, QkGate_U3, QkGate_CH, QkGate_CX, QkGate_CY, QkGate_CZ, QkGate_DCX, QkGate_ECR, &
      QkGate_Swap, QkGate_ISwap, QkGate_CPhase, QkGate_CRX, QkGate_CRY, QkGate_CRZ, QkGate_CS, QkGate_CSdg, QkGate_CSX, &
      QkGate_CU, QkGate_CU1, QkGate_CU3, QkGate_RXX, QkGate_RYY, QkGate_RZZ, QkGate_RZX, QkGate_XXMinusYY, QkGate_XXPlusYY, &
      QkGate_CCX, QkGate_CCZ, QkGate_CSwap, QkGate_RCCX, QkGate_C3X, QkGate_C3SX, QkGate_RC3X, QkOperationKind_Gate, &
      QkOperationKind_Barrier, QkOperationKind_Delay, QkOperationKind_Measure, QkOperationKind_Reset, QkOperationKind_Unitary, &
      QkOperationKind_PauliProductMeasurement, QkOperationKind_ControlFlow, QkOperationKind_Unknown, &
      QkOperationKind_PauliProductRotation, QkDelayUnit_S, QkDelayUnit_MS, QkDelayUnit_US, QkDelayUnit_NS, QkDelayUnit_PS, &
      QkVarsMode_Alike, QkVarsMode_Captures, QkVarsMode_Drop, QkBlocksMode_Drop, QkBlocksMode_Keep, QkDagNodeType_Operation, &
      QkDagNodeType_QubitIn, QkDagNodeType_QubitOut, QkDagNodeType_ClbitIn, QkDagNodeType_ClbitOut, QkDagNodeType_VarIn, &
      QkDagNodeType_VarOut, QkBitTerm_X, QkBitTerm_Plus, QkBitTerm_Minus, QkBitTerm_Y, QkBitTerm_Right, QkBitTerm_Left, &
      QkBitTerm_Z, QkBitTerm_Zero, QkBitTerm_One, qk_complex64_to_native, qk_complex64_from_native, qk_api_version, &
      qk_circuit_new, qk_quantum_register_new, qk_quantum_register_free, qk_classical_register_free, qk_classical_register_new, &
      qk_circuit_add_quantum_register, qk_circuit_add_classical_register, qk_circuit_copy, qk_circuit_num_qubits, &
      qk_circuit_num_clbits, qk_circuit_num_param_symbols, qk_circuit_free, qk_circuit_gate, qk_circuit_parameterized_gate, &
      qk_gate_num_qubits, qk_gate_num_params, qk_circuit_measure, qk_circuit_reset, qk_circuit_barrier, qk_circuit_unitary, &
      qk_circuit_inst_unitary, qk_circuit_instruction_kind, qk_circuit_count_ops, qk_circuit_num_instructions, &
      qk_circuit_get_instruction, qk_circuit_pauli_product_rotation, qk_circuit_inst_pauli_product_rotation, &
      qk_circuit_pauli_product_measurement, qk_circuit_inst_pauli_product_measurement, qk_circuit_instruction_clear, &
      qk_opcounts_clear, qk_circuit_delay, qk_circuit_draw, qk_circuit_to_dag, qk_circuit_copy_empty_like, &
      qk_circuit_library_iqp, qk_circuit_library_random_iqp, qk_pauli_product_rotation_clear, qk_pauli_product_measurement_clear, &
      qk_circuit_library_quantum_volume, qk_circuit_library_suzuki_trotter, qk_dag_new, qk_dag_add_quantum_register, &
      qk_dag_add_classical_register, qk_dag_num_qubits, qk_dag_num_clbits, qk_dag_num_op_nodes, qk_dag_node_type, &
      qk_dag_qubit_in_node, qk_dag_qubit_out_node, qk_dag_clbit_in_node, qk_dag_clbit_out_node, qk_dag_wire_node_value, &
      qk_dag_op_node_num_qubits, qk_dag_op_node_num_clbits, qk_dag_op_node_num_params, qk_dag_op_node_qubits, &
      qk_dag_op_node_clbits, qk_dag_apply_gate, qk_dag_apply_measure, qk_dag_apply_reset, qk_dag_apply_barrier, &
      qk_dag_apply_unitary, qk_dag_op_node_gate_op, qk_dag_op_node_unitary, qk_dag_op_node_kind, qk_dag_successors, &
      qk_dag_predecessors, qk_dag_neighbors_clear, qk_dag_get_instruction, qk_dag_compose, qk_dag_free, qk_dag_to_circuit, &
      qk_dag_topological_op_nodes, qk_dag_substitute_node_with_dag, qk_dag_copy_empty_like, qk_dag_replace_block_with_unitary, &
      qk_dag_substitute_node_with_unitary, qk_param_new_symbol, qk_param_zero, qk_param_free, qk_param_from_double, &
      qk_param_from_complex, qk_param_copy, qk_param_str, qk_param_add, qk_param_sub, qk_param_mul, qk_param_div, qk_param_pow, &
      qk_param_sin, qk_param_cos, qk_param_tan, qk_param_asin, qk_param_acos, qk_param_atan, qk_param_log, qk_param_exp, &
      qk_param_abs, qk_param_sign, qk_param_neg, qk_param_conjugate, qk_param_equal, qk_param_as_real, qk_obs_zero, &
      qk_obs_identity, qk_obs_new, qk_obs_free, qk_obs_add_term, qk_obs_term, qk_obs_num_terms, qk_obs_num_qubits, qk_obs_len, &
      qk_obs_coeffs, qk_obs_indices, qk_obs_boundaries, qk_obs_bit_terms, qk_obs_multiply, qk_obs_multiply_inplace, qk_obs_add, &
      qk_obs_add_inplace, qk_obs_scaled_add, qk_obs_scaled_add_inplace, qk_obs_compose, qk_obs_compose_map, qk_obs_apply_layout, &
      qk_obs_canonicalize, qk_obs_copy, qk_obs_equal, qk_obs_str, qk_str_free, qk_obsterm_str, qk_bitterm_label, &
      qk_neighbors_is_all_to_all, qk_neighbors_from_target, qk_neighbors_clear, qk_transpiler_pass_standalone_basis_translator, &
      qk_transpiler_pass_standalone_commutative_cancellation, qk_transpiler_pass_standalone_consolidate_blocks, &
      qk_transpiler_pass_standalone_convert_to_pauli_rotations, qk_transpiler_pass_standalone_elide_permutations, &
      qk_transpiler_pass_elide_permutations, qk_transpiler_pass_standalone_check_gate_direction, &
      qk_transpiler_pass_standalone_gate_direction, qk_transpiler_pass_check_gate_direction, qk_transpiler_pass_gate_direction, &
      qk_transpiler_pass_standalone_inverse_cancellation, qk_transpiler_pass_standalone_litinski_transformation, &
      qk_transpiler_standalone_optimize_1q_sequences, qk_transpiler_pass_standalone_optimize_1q_sequences, &
      qk_transpiler_pass_optimize_1q_sequences, qk_transpiler_pass_standalone_remove_diagonal_gates_befor1RUDHG, &
      qk_transpiler_pass_remove_diagonal_gates_before_measure, qk_transpiler_pass_standalone_remove_identity_equivalent, &
      qk_transpiler_pass_remove_identity_equivalent, qk_sabre_layout_options_default, qk_transpiler_pass_standalone_sabre_layout, &
      qk_transpiler_pass_standalone_split_2q_unitaries, qk_transpiler_pass_split_2q_unitaries, &
      qk_transpiler_pass_standalone_unitary_synthesis, qk_vf2_layout_result_has_match, qk_vf2_layout_result_has_improvement, &
      qk_vf2_layout_result_map_virtual_qubit, qk_vf2_layout_result_free, qk_vf2_layout_configuration_new, &
      qk_vf2_layout_configuration_free, qk_vf2_layout_configuration_set_call_limit, qk_vf2_layout_configuration_set_time_limit, &
      qk_vf2_layout_configuration_set_max_trials, qk_vf2_layout_configuration_set_shuffle_seed, &
      qk_vf2_layout_configuration_set_score_initial, qk_transpiler_pass_standalone_vf2_layout_average, &
      qk_transpiler_pass_standalone_vf2_layout_exact, qk_transpiler_pass_standalone_vf2_layout, qk_target_new, &
      qk_target_num_qubits, qk_target_dt, qk_target_granularity, qk_target_min_length, qk_target_pulse_alignment, &
      qk_target_acquire_alignment, qk_target_set_dt, qk_target_set_granularity, qk_target_set_min_length, &
      qk_target_set_pulse_alignment, qk_target_set_acquire_alignment, qk_target_copy, qk_target_free, qk_target_entry_new, &
      qk_target_entry_new_measure, qk_target_entry_new_reset, qk_target_entry_new_fixed, qk_target_entry_num_properties, &
      qk_target_entry_free, qk_target_entry_add_property, qk_target_entry_set_name, qk_target_add_instruction, &
      qk_target_update_property, qk_target_num_instructions, qk_target_instruction_supported, qk_target_op_index, &
      qk_target_op_name, qk_target_op_num_properties, qk_target_op_qargs_index, qk_target_op_qargs, qk_target_op_props, &
      qk_target_op_get, qk_target_op_gate, qk_target_op_clear, qk_transpile_state_new, qk_transpile_state_free, &
      qk_transpile_state_layout, qk_transpile_state_layout_set, qk_transpiler_default_options, qk_transpile_stage_init, &
      qk_transpile_stage_routing, qk_transpile_stage_optimization, qk_transpile_stage_translation, qk_transpile_stage_layout, &
      qk_transpile, qk_transpile_layout_num_input_qubits, qk_transpile_layout_num_output_qubits, &
      qk_transpile_layout_initial_layout, qk_transpile_layout_output_permutation, qk_transpile_layout_final_layout, &
      qk_transpile_layout_generate_from_mapping, qk_transpile_layout_free, QK_QUBIT_KIND

  integer(c_int), parameter :: QkExitCode_Success = 0_c_int
  integer(c_int), parameter :: QkExitCode_CInputError = 100_c_int
  integer(c_int), parameter :: QkExitCode_NullPointerError = 101_c_int
  integer(c_int), parameter :: QkExitCode_AlignmentError = 102_c_int
  integer(c_int), parameter :: QkExitCode_IndexError = 103_c_int
  integer(c_int), parameter :: QkExitCode_DuplicateIndexError = 104_c_int
  integer(c_int), parameter :: QkExitCode_InvalidOperationKind = 105_c_int
  integer(c_int), parameter :: QkExitCode_ArithmeticError = 200_c_int
  integer(c_int), parameter :: QkExitCode_MismatchedQubits = 201_c_int
  integer(c_int), parameter :: QkExitCode_ExpectedUnitary = 202_c_int
  integer(c_int), parameter :: QkExitCode_TargetError = 300_c_int
  integer(c_int), parameter :: QkExitCode_TargetInstAlreadyExists = 301_c_int
  integer(c_int), parameter :: QkExitCode_TargetQargMismatch = 302_c_int
  integer(c_int), parameter :: QkExitCode_TargetInvalidQargsKey = 303_c_int
  integer(c_int), parameter :: QkExitCode_TargetInvalidInstKey = 304_c_int
  integer(c_int), parameter :: QkExitCode_TranspilerError = 400_c_int
  integer(c_int), parameter :: QkExitCode_DagError = 500_c_int
  integer(c_int), parameter :: QkExitCode_DagComposeMismatch = 501_c_int
  integer(c_int), parameter :: QkExitCode_DagComposeMissingBit = 502_c_int
  integer(c_int), parameter :: QkExitCode_ParameterError = 600_c_int
  integer(c_int), parameter :: QkExitCode_ParameterNameConflict = 601_c_int
  integer(c_int), parameter :: QkGate_GlobalPhase = 0_c_int
  integer(c_int), parameter :: QkGate_H = 1_c_int
  integer(c_int), parameter :: QkGate_I = 2_c_int
  integer(c_int), parameter :: QkGate_X = 3_c_int
  integer(c_int), parameter :: QkGate_Y = 4_c_int
  integer(c_int), parameter :: QkGate_Z = 5_c_int
  integer(c_int), parameter :: QkGate_Phase = 6_c_int
  integer(c_int), parameter :: QkGate_R = 7_c_int
  integer(c_int), parameter :: QkGate_RX = 8_c_int
  integer(c_int), parameter :: QkGate_RY = 9_c_int
  integer(c_int), parameter :: QkGate_RZ = 10_c_int
  integer(c_int), parameter :: QkGate_S = 11_c_int
  integer(c_int), parameter :: QkGate_Sdg = 12_c_int
  integer(c_int), parameter :: QkGate_SX = 13_c_int
  integer(c_int), parameter :: QkGate_SXdg = 14_c_int
  integer(c_int), parameter :: QkGate_T = 15_c_int
  integer(c_int), parameter :: QkGate_Tdg = 16_c_int
  integer(c_int), parameter :: QkGate_U = 17_c_int
  integer(c_int), parameter :: QkGate_U1 = 18_c_int
  integer(c_int), parameter :: QkGate_U2 = 19_c_int
  integer(c_int), parameter :: QkGate_U3 = 20_c_int
  integer(c_int), parameter :: QkGate_CH = 21_c_int
  integer(c_int), parameter :: QkGate_CX = 22_c_int
  integer(c_int), parameter :: QkGate_CY = 23_c_int
  integer(c_int), parameter :: QkGate_CZ = 24_c_int
  integer(c_int), parameter :: QkGate_DCX = 25_c_int
  integer(c_int), parameter :: QkGate_ECR = 26_c_int
  integer(c_int), parameter :: QkGate_Swap = 27_c_int
  integer(c_int), parameter :: QkGate_ISwap = 28_c_int
  integer(c_int), parameter :: QkGate_CPhase = 29_c_int
  integer(c_int), parameter :: QkGate_CRX = 30_c_int
  integer(c_int), parameter :: QkGate_CRY = 31_c_int
  integer(c_int), parameter :: QkGate_CRZ = 32_c_int
  integer(c_int), parameter :: QkGate_CS = 33_c_int
  integer(c_int), parameter :: QkGate_CSdg = 34_c_int
  integer(c_int), parameter :: QkGate_CSX = 35_c_int
  integer(c_int), parameter :: QkGate_CU = 36_c_int
  integer(c_int), parameter :: QkGate_CU1 = 37_c_int
  integer(c_int), parameter :: QkGate_CU3 = 38_c_int
  integer(c_int), parameter :: QkGate_RXX = 39_c_int
  integer(c_int), parameter :: QkGate_RYY = 40_c_int
  integer(c_int), parameter :: QkGate_RZZ = 41_c_int
  integer(c_int), parameter :: QkGate_RZX = 42_c_int
  integer(c_int), parameter :: QkGate_XXMinusYY = 43_c_int
  integer(c_int), parameter :: QkGate_XXPlusYY = 44_c_int
  integer(c_int), parameter :: QkGate_CCX = 45_c_int
  integer(c_int), parameter :: QkGate_CCZ = 46_c_int
  integer(c_int), parameter :: QkGate_CSwap = 47_c_int
  integer(c_int), parameter :: QkGate_RCCX = 48_c_int
  integer(c_int), parameter :: QkGate_C3X = 49_c_int
  integer(c_int), parameter :: QkGate_C3SX = 50_c_int
  integer(c_int), parameter :: QkGate_RC3X = 51_c_int
  integer(c_int), parameter :: QkOperationKind_Gate = 0_c_int
  integer(c_int), parameter :: QkOperationKind_Barrier = 1_c_int
  integer(c_int), parameter :: QkOperationKind_Delay = 2_c_int
  integer(c_int), parameter :: QkOperationKind_Measure = 3_c_int
  integer(c_int), parameter :: QkOperationKind_Reset = 4_c_int
  integer(c_int), parameter :: QkOperationKind_Unitary = 5_c_int
  integer(c_int), parameter :: QkOperationKind_PauliProductMeasurement = 6_c_int
  integer(c_int), parameter :: QkOperationKind_ControlFlow = 7_c_int
  integer(c_int), parameter :: QkOperationKind_Unknown = 8_c_int
  integer(c_int), parameter :: QkOperationKind_PauliProductRotation = 9_c_int
  integer(c_int), parameter :: QkDelayUnit_S = 0_c_int
  integer(c_int), parameter :: QkDelayUnit_MS = 1_c_int
  integer(c_int), parameter :: QkDelayUnit_US = 2_c_int
  integer(c_int), parameter :: QkDelayUnit_NS = 3_c_int
  integer(c_int), parameter :: QkDelayUnit_PS = 4_c_int
  integer(c_int), parameter :: QkVarsMode_Alike = 0_c_int
  integer(c_int), parameter :: QkVarsMode_Captures = 1_c_int
  integer(c_int), parameter :: QkVarsMode_Drop = 2_c_int
  integer(c_int), parameter :: QkBlocksMode_Drop = 0_c_int
  integer(c_int), parameter :: QkBlocksMode_Keep = 1_c_int
  integer(c_int), parameter :: QkDagNodeType_Operation = 0_c_int
  integer(c_int), parameter :: QkDagNodeType_QubitIn = 1_c_int
  integer(c_int), parameter :: QkDagNodeType_QubitOut = 2_c_int
  integer(c_int), parameter :: QkDagNodeType_ClbitIn = 3_c_int
  integer(c_int), parameter :: QkDagNodeType_ClbitOut = 4_c_int
  integer(c_int), parameter :: QkDagNodeType_VarIn = 5_c_int
  integer(c_int), parameter :: QkDagNodeType_VarOut = 6_c_int
  integer(c_int), parameter :: QkBitTerm_X = 2_c_int
  integer(c_int), parameter :: QkBitTerm_Plus = 10_c_int
  integer(c_int), parameter :: QkBitTerm_Minus = 6_c_int
  integer(c_int), parameter :: QkBitTerm_Y = 3_c_int
  integer(c_int), parameter :: QkBitTerm_Right = 11_c_int
  integer(c_int), parameter :: QkBitTerm_Left = 7_c_int
  integer(c_int), parameter :: QkBitTerm_Z = 1_c_int
  integer(c_int), parameter :: QkBitTerm_Zero = 9_c_int
  integer(c_int), parameter :: QkBitTerm_One = 5_c_int

  ! C-interoperable kind for uint32_t qubit/clbit indices
  integer, parameter :: QK_QUBIT_KIND = c_int32_t

  interface

    function qk_complex64_to_native(value) result(ptr) &
        bind(C, name="qk_complex64_to_native")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: value
      type(c_ptr) :: ptr
    end function qk_complex64_to_native

    function qk_complex64_from_native(value) result(ptr) &
        bind(C, name="qk_complex64_from_native")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: value
      type(c_ptr) :: ptr
    end function qk_complex64_from_native

    function qk_api_version() result(n) &
        bind(C, name="qk_api_version")
      import :: c_int32_t
      integer(c_int32_t) :: n
    end function qk_api_version

    function qk_circuit_new(num_qubits, num_clbits) result(ptr) &
        bind(C, name="qk_circuit_new")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      integer(c_int32_t), value, intent(in) :: num_clbits
      type(c_ptr) :: ptr
    end function qk_circuit_new

    function qk_quantum_register_new(num_qubits, name) result(ptr) &
        bind(C, name="qk_quantum_register_new")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: name
      type(c_ptr) :: ptr
    end function qk_quantum_register_new

    subroutine qk_quantum_register_free(reg) &
        bind(C, name="qk_quantum_register_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: reg
    end subroutine qk_quantum_register_free

    subroutine qk_classical_register_free(reg) &
        bind(C, name="qk_classical_register_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: reg
    end subroutine qk_classical_register_free

    function qk_classical_register_new(num_clbits, name) result(ptr) &
        bind(C, name="qk_classical_register_new")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_clbits
      type(c_ptr), value, intent(in) :: name
      type(c_ptr) :: ptr
    end function qk_classical_register_new

    subroutine qk_circuit_add_quantum_register(circuit, reg) &
        bind(C, name="qk_circuit_add_quantum_register")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: reg
    end subroutine qk_circuit_add_quantum_register

    subroutine qk_circuit_add_classical_register(circuit, reg) &
        bind(C, name="qk_circuit_add_classical_register")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: reg
    end subroutine qk_circuit_add_classical_register

    function qk_circuit_copy(circuit) result(ptr) &
        bind(C, name="qk_circuit_copy")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr) :: ptr
    end function qk_circuit_copy

    function qk_circuit_num_qubits(circuit) result(n) &
        bind(C, name="qk_circuit_num_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      integer(c_int32_t) :: n
    end function qk_circuit_num_qubits

    function qk_circuit_num_clbits(circuit) result(n) &
        bind(C, name="qk_circuit_num_clbits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      integer(c_int32_t) :: n
    end function qk_circuit_num_clbits

    function qk_circuit_num_param_symbols(circuit) result(n) &
        bind(C, name="qk_circuit_num_param_symbols")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: circuit
      integer(c_size_t) :: n
    end function qk_circuit_num_param_symbols

    subroutine qk_circuit_free(circuit) &
        bind(C, name="qk_circuit_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
    end subroutine qk_circuit_free

    function qk_circuit_gate(circuit, gate, qubits, params) result(code) &
        bind(C, name="qk_circuit_gate")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: circuit
      integer(c_int), value, intent(in) :: gate
      type(c_ptr), value, intent(in) :: qubits
      type(c_ptr), value, intent(in) :: params
      integer(c_int) :: code
    end function qk_circuit_gate

    function qk_circuit_parameterized_gate(circuit, gate, qubits, params) result(code) &
        bind(C, name="qk_circuit_parameterized_gate")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: circuit
      integer(c_int), value, intent(in) :: gate
      type(c_ptr), value, intent(in) :: qubits
      type(c_ptr), value, intent(in) :: params
      integer(c_int) :: code
    end function qk_circuit_parameterized_gate

    function qk_gate_num_qubits(gate) result(n) &
        bind(C, name="qk_gate_num_qubits")
      import :: c_int, c_int32_t
      integer(c_int), value, intent(in) :: gate
      integer(c_int32_t) :: n
    end function qk_gate_num_qubits

    function qk_gate_num_params(gate) result(n) &
        bind(C, name="qk_gate_num_params")
      import :: c_int, c_int32_t
      integer(c_int), value, intent(in) :: gate
      integer(c_int32_t) :: n
    end function qk_gate_num_params

    function qk_circuit_measure(circuit, qubit, clbit) result(code) &
        bind(C, name="qk_circuit_measure")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      integer(c_int32_t), value, intent(in) :: qubit
      integer(c_int32_t), value, intent(in) :: clbit
      integer(c_int) :: code
    end function qk_circuit_measure

    function qk_circuit_reset(circuit, qubit) result(code) &
        bind(C, name="qk_circuit_reset")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      integer(c_int32_t), value, intent(in) :: qubit
      integer(c_int) :: code
    end function qk_circuit_reset

    function qk_circuit_barrier(circuit, qubits, num_qubits) result(code) &
        bind(C, name="qk_circuit_barrier")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: qubits
      integer(c_int32_t), value, intent(in) :: num_qubits
      integer(c_int) :: code
    end function qk_circuit_barrier

    function qk_circuit_unitary(circuit, matrix, qubits, num_qubits, check_input) result(code) &
        bind(C, name="qk_circuit_unitary")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: matrix
      type(c_ptr), value, intent(in) :: qubits
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: check_input
      integer(c_int) :: code
    end function qk_circuit_unitary

    subroutine qk_circuit_inst_unitary(circuit, index, out) &
        bind(C, name="qk_circuit_inst_unitary")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: index
      type(c_ptr), value, intent(in) :: out
    end subroutine qk_circuit_inst_unitary

    function qk_circuit_instruction_kind(circuit, index) result(code) &
        bind(C, name="qk_circuit_instruction_kind")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: index
      integer(c_int) :: code
    end function qk_circuit_instruction_kind

    function qk_circuit_count_ops(circuit) result(ptr) &
        bind(C, name="qk_circuit_count_ops")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr) :: ptr
    end function qk_circuit_count_ops

    function qk_circuit_num_instructions(circuit) result(n) &
        bind(C, name="qk_circuit_num_instructions")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: circuit
      integer(c_size_t) :: n
    end function qk_circuit_num_instructions

    subroutine qk_circuit_get_instruction(circuit, index, instruction) &
        bind(C, name="qk_circuit_get_instruction")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: index
      type(c_ptr), value, intent(in) :: instruction
    end subroutine qk_circuit_get_instruction

    subroutine qk_circuit_pauli_product_rotation(circuit, rotation, qubits) &
        bind(C, name="qk_circuit_pauli_product_rotation")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: rotation
      type(c_ptr), value, intent(in) :: qubits
    end subroutine qk_circuit_pauli_product_rotation

    function qk_circuit_inst_pauli_product_rotation(circuit, index, instruction) result(code) &
        bind(C, name="qk_circuit_inst_pauli_product_rotation")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: index
      type(c_ptr), value, intent(in) :: instruction
      integer(c_int) :: code
    end function qk_circuit_inst_pauli_product_rotation

    subroutine qk_circuit_pauli_product_measurement(circuit, measurement, qubits, clbit) &
        bind(C, name="qk_circuit_pauli_product_measurement")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: measurement
      type(c_ptr), value, intent(in) :: qubits
      integer(c_int32_t), value, intent(in) :: clbit
    end subroutine qk_circuit_pauli_product_measurement

    function qk_circuit_inst_pauli_product_measurement(circuit, index, instruction) result(code) &
        bind(C, name="qk_circuit_inst_pauli_product_measurement")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: index
      type(c_ptr), value, intent(in) :: instruction
      integer(c_int) :: code
    end function qk_circuit_inst_pauli_product_measurement

    subroutine qk_circuit_instruction_clear(inst) &
        bind(C, name="qk_circuit_instruction_clear")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: inst
    end subroutine qk_circuit_instruction_clear

    subroutine qk_opcounts_clear(op_counts) &
        bind(C, name="qk_opcounts_clear")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: op_counts
    end subroutine qk_opcounts_clear

    function qk_circuit_delay(circuit, qubit, duration, unit) result(code) &
        bind(C, name="qk_circuit_delay")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: circuit
      integer(c_int32_t), value, intent(in) :: qubit
      type(c_ptr), value, intent(in) :: duration
      integer(c_int), value, intent(in) :: unit
      integer(c_int) :: code
    end function qk_circuit_delay

    function qk_circuit_draw(circuit, config) result(result) &
        bind(C, name="qk_circuit_draw")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: config
      type(c_ptr) :: result
    end function qk_circuit_draw

    function qk_circuit_to_dag(circuit) result(ptr) &
        bind(C, name="qk_circuit_to_dag")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr) :: ptr
    end function qk_circuit_to_dag

    function qk_circuit_copy_empty_like(circuit, vars_mode, blocks_mode) result(ptr) &
        bind(C, name="qk_circuit_copy_empty_like")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: vars_mode
      type(c_ptr), value, intent(in) :: blocks_mode
      type(c_ptr) :: ptr
    end function qk_circuit_copy_empty_like

    function qk_circuit_library_iqp(num_qubits, interactions, check_input) result(ptr) &
        bind(C, name="qk_circuit_library_iqp")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: interactions
      type(c_ptr), value, intent(in) :: check_input
      type(c_ptr) :: ptr
    end function qk_circuit_library_iqp

    function qk_circuit_library_random_iqp(num_qubits, seed) result(ptr) &
        bind(C, name="qk_circuit_library_random_iqp")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      integer(c_int32_t), value, intent(in) :: seed
      type(c_ptr) :: ptr
    end function qk_circuit_library_random_iqp

    subroutine qk_pauli_product_rotation_clear(inst) &
        bind(C, name="qk_pauli_product_rotation_clear")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: inst
    end subroutine qk_pauli_product_rotation_clear

    subroutine qk_pauli_product_measurement_clear(inst) &
        bind(C, name="qk_pauli_product_measurement_clear")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: inst
    end subroutine qk_pauli_product_measurement_clear

    function qk_circuit_library_quantum_volume(num_qubits, depth, seed) result(ptr) &
        bind(C, name="qk_circuit_library_quantum_volume")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: depth
      integer(c_int32_t), value, intent(in) :: seed
      type(c_ptr) :: ptr
    end function qk_circuit_library_quantum_volume

    function qk_circuit_library_suzuki_trotter(op, order, reps, time, preserve_order, insert_barriers) result(ptr) &
        bind(C, name="qk_circuit_library_suzuki_trotter")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: op
      integer(c_int32_t), value, intent(in) :: order
      integer(c_int32_t), value, intent(in) :: reps
      type(c_ptr), value, intent(in) :: time
      type(c_ptr), value, intent(in) :: preserve_order
      type(c_ptr), value, intent(in) :: insert_barriers
      type(c_ptr) :: ptr
    end function qk_circuit_library_suzuki_trotter

    function qk_dag_new() result(ptr) &
        bind(C, name="qk_dag_new")
      import :: c_ptr
      type(c_ptr) :: ptr
    end function qk_dag_new

    subroutine qk_dag_add_quantum_register(dag, reg) &
        bind(C, name="qk_dag_add_quantum_register")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: reg
    end subroutine qk_dag_add_quantum_register

    subroutine qk_dag_add_classical_register(dag, reg) &
        bind(C, name="qk_dag_add_classical_register")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: reg
    end subroutine qk_dag_add_classical_register

    function qk_dag_num_qubits(dag) result(n) &
        bind(C, name="qk_dag_num_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t) :: n
    end function qk_dag_num_qubits

    function qk_dag_num_clbits(dag) result(n) &
        bind(C, name="qk_dag_num_clbits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t) :: n
    end function qk_dag_num_clbits

    function qk_dag_num_op_nodes(dag) result(n) &
        bind(C, name="qk_dag_num_op_nodes")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_size_t) :: n
    end function qk_dag_num_op_nodes

    function qk_dag_node_type(dag, node) result(ptr) &
        bind(C, name="qk_dag_node_type")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      type(c_ptr) :: ptr
    end function qk_dag_node_type

    function qk_dag_qubit_in_node(dag, qubit) result(n) &
        bind(C, name="qk_dag_qubit_in_node")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: qubit
      integer(c_int32_t) :: n
    end function qk_dag_qubit_in_node

    function qk_dag_qubit_out_node(dag, qubit) result(n) &
        bind(C, name="qk_dag_qubit_out_node")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: qubit
      integer(c_int32_t) :: n
    end function qk_dag_qubit_out_node

    function qk_dag_clbit_in_node(dag, clbit) result(n) &
        bind(C, name="qk_dag_clbit_in_node")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: clbit
      integer(c_int32_t) :: n
    end function qk_dag_clbit_in_node

    function qk_dag_clbit_out_node(dag, clbit) result(n) &
        bind(C, name="qk_dag_clbit_out_node")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: clbit
      integer(c_int32_t) :: n
    end function qk_dag_clbit_out_node

    function qk_dag_wire_node_value(dag, node) result(n) &
        bind(C, name="qk_dag_wire_node_value")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      integer(c_int32_t) :: n
    end function qk_dag_wire_node_value

    function qk_dag_op_node_num_qubits(dag, node) result(n) &
        bind(C, name="qk_dag_op_node_num_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      integer(c_int32_t) :: n
    end function qk_dag_op_node_num_qubits

    function qk_dag_op_node_num_clbits(dag, node) result(n) &
        bind(C, name="qk_dag_op_node_num_clbits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      integer(c_int32_t) :: n
    end function qk_dag_op_node_num_clbits

    function qk_dag_op_node_num_params(dag, node) result(n) &
        bind(C, name="qk_dag_op_node_num_params")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      integer(c_int32_t) :: n
    end function qk_dag_op_node_num_params

    function qk_dag_op_node_qubits(dag, node) result(n) &
        bind(C, name="qk_dag_op_node_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      integer(c_int32_t) :: n
    end function qk_dag_op_node_qubits

    function qk_dag_op_node_clbits(dag, node) result(n) &
        bind(C, name="qk_dag_op_node_clbits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      integer(c_int32_t) :: n
    end function qk_dag_op_node_clbits

    function qk_dag_apply_gate(dag, gate, qubits, params, front) result(n) &
        bind(C, name="qk_dag_apply_gate")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int), value, intent(in) :: gate
      type(c_ptr), value, intent(in) :: qubits
      type(c_ptr), value, intent(in) :: params
      type(c_ptr), value, intent(in) :: front
      integer(c_int32_t) :: n
    end function qk_dag_apply_gate

    function qk_dag_apply_measure(dag, qubit, clbit, front) result(n) &
        bind(C, name="qk_dag_apply_measure")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: qubit
      integer(c_int32_t), value, intent(in) :: clbit
      type(c_ptr), value, intent(in) :: front
      integer(c_int32_t) :: n
    end function qk_dag_apply_measure

    function qk_dag_apply_reset(dag, qubit, front) result(n) &
        bind(C, name="qk_dag_apply_reset")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: qubit
      type(c_ptr), value, intent(in) :: front
      integer(c_int32_t) :: n
    end function qk_dag_apply_reset

    function qk_dag_apply_barrier(dag, qubits, num_qubits, front) result(n) &
        bind(C, name="qk_dag_apply_barrier")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: qubits
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: front
      integer(c_int32_t) :: n
    end function qk_dag_apply_barrier

    function qk_dag_apply_unitary(dag, matrix, qubits, num_qubits, front) result(n) &
        bind(C, name="qk_dag_apply_unitary")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: matrix
      type(c_ptr), value, intent(in) :: qubits
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: front
      integer(c_int32_t) :: n
    end function qk_dag_apply_unitary

    function qk_dag_op_node_gate_op(dag, node, out_params) result(code) &
        bind(C, name="qk_dag_op_node_gate_op")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      type(c_ptr), value, intent(in) :: out_params
      integer(c_int) :: code
    end function qk_dag_op_node_gate_op

    subroutine qk_dag_op_node_unitary(dag, node, out) &
        bind(C, name="qk_dag_op_node_unitary")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      type(c_ptr), value, intent(in) :: out
    end subroutine qk_dag_op_node_unitary

    function qk_dag_op_node_kind(dag, node) result(code) &
        bind(C, name="qk_dag_op_node_kind")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      integer(c_int) :: code
    end function qk_dag_op_node_kind

    function qk_dag_successors(dag, node) result(ptr) &
        bind(C, name="qk_dag_successors")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      type(c_ptr) :: ptr
    end function qk_dag_successors

    function qk_dag_predecessors(dag, node) result(ptr) &
        bind(C, name="qk_dag_predecessors")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      type(c_ptr) :: ptr
    end function qk_dag_predecessors

    subroutine qk_dag_neighbors_clear(neighbors) &
        bind(C, name="qk_dag_neighbors_clear")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: neighbors
    end subroutine qk_dag_neighbors_clear

    subroutine qk_dag_get_instruction(dag, index, instruction) &
        bind(C, name="qk_dag_get_instruction")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: index
      type(c_ptr), value, intent(in) :: instruction
    end subroutine qk_dag_get_instruction

    function qk_dag_compose(dag, other, qubits, clbits) result(code) &
        bind(C, name="qk_dag_compose")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: other
      type(c_ptr), value, intent(in) :: qubits
      type(c_ptr), value, intent(in) :: clbits
      integer(c_int) :: code
    end function qk_dag_compose

    subroutine qk_dag_free(dag) &
        bind(C, name="qk_dag_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
    end subroutine qk_dag_free

    function qk_dag_to_circuit(dag) result(ptr) &
        bind(C, name="qk_dag_to_circuit")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr) :: ptr
    end function qk_dag_to_circuit

    subroutine qk_dag_topological_op_nodes(dag, out_order) &
        bind(C, name="qk_dag_topological_op_nodes")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: out_order
    end subroutine qk_dag_topological_op_nodes

    subroutine qk_dag_substitute_node_with_dag(dag, node, replacement) &
        bind(C, name="qk_dag_substitute_node_with_dag")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      type(c_ptr), value, intent(in) :: replacement
    end subroutine qk_dag_substitute_node_with_dag

    function qk_dag_copy_empty_like(dag, vars_mode, blocks_mode) result(ptr) &
        bind(C, name="qk_dag_copy_empty_like")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: vars_mode
      type(c_ptr), value, intent(in) :: blocks_mode
      type(c_ptr) :: ptr
    end function qk_dag_copy_empty_like

    function qk_dag_replace_block_with_unitary(&
        dag, &
        num_block_ids, &
        block_ids, &
        matrix, &
        num_qubits, &
        qubits, &
        cycle_check) result(n) &
        bind(C, name="qk_dag_replace_block_with_unitary")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: num_block_ids
      type(c_ptr), value, intent(in) :: block_ids
      type(c_ptr), value, intent(in) :: matrix
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: qubits
      type(c_ptr), value, intent(in) :: cycle_check
      integer(c_int32_t) :: n
    end function qk_dag_replace_block_with_unitary

    subroutine qk_dag_substitute_node_with_unitary(dag, node, matrix, num_qubits) &
        bind(C, name="qk_dag_substitute_node_with_unitary")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: dag
      integer(c_int32_t), value, intent(in) :: node
      type(c_ptr), value, intent(in) :: matrix
      integer(c_int32_t), value, intent(in) :: num_qubits
    end subroutine qk_dag_substitute_node_with_unitary

    function qk_param_new_symbol(name) result(ptr) &
        bind(C, name="qk_param_new_symbol")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: name
      type(c_ptr) :: ptr
    end function qk_param_new_symbol

    function qk_param_zero() result(ptr) &
        bind(C, name="qk_param_zero")
      import :: c_ptr
      type(c_ptr) :: ptr
    end function qk_param_zero

    subroutine qk_param_free(param) &
        bind(C, name="qk_param_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: param
    end subroutine qk_param_free

    function qk_param_from_double(value) result(ptr) &
        bind(C, name="qk_param_from_double")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: value
      type(c_ptr) :: ptr
    end function qk_param_from_double

    function qk_param_from_complex(value) result(ptr) &
        bind(C, name="qk_param_from_complex")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: value
      type(c_ptr) :: ptr
    end function qk_param_from_complex

    function qk_param_copy(param) result(ptr) &
        bind(C, name="qk_param_copy")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: param
      type(c_ptr) :: ptr
    end function qk_param_copy

    function qk_param_str(param) result(result) &
        bind(C, name="qk_param_str")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: param
      type(c_ptr) :: result
    end function qk_param_str

    function qk_param_add(out, lhs, rhs) result(code) &
        bind(C, name="qk_param_add")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: lhs
      type(c_ptr), value, intent(in) :: rhs
      integer(c_int) :: code
    end function qk_param_add

    function qk_param_sub(out, lhs, rhs) result(code) &
        bind(C, name="qk_param_sub")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: lhs
      type(c_ptr), value, intent(in) :: rhs
      integer(c_int) :: code
    end function qk_param_sub

    function qk_param_mul(out, lhs, rhs) result(code) &
        bind(C, name="qk_param_mul")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: lhs
      type(c_ptr), value, intent(in) :: rhs
      integer(c_int) :: code
    end function qk_param_mul

    function qk_param_div(out, num, den) result(code) &
        bind(C, name="qk_param_div")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: num
      type(c_ptr), value, intent(in) :: den
      integer(c_int) :: code
    end function qk_param_div

    function qk_param_pow(out, base, pow) result(code) &
        bind(C, name="qk_param_pow")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: base
      type(c_ptr), value, intent(in) :: pow
      integer(c_int) :: code
    end function qk_param_pow

    function qk_param_sin(out, src) result(code) &
        bind(C, name="qk_param_sin")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_sin

    function qk_param_cos(out, src) result(code) &
        bind(C, name="qk_param_cos")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_cos

    function qk_param_tan(out, src) result(code) &
        bind(C, name="qk_param_tan")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_tan

    function qk_param_asin(out, src) result(code) &
        bind(C, name="qk_param_asin")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_asin

    function qk_param_acos(out, src) result(code) &
        bind(C, name="qk_param_acos")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_acos

    function qk_param_atan(out, src) result(code) &
        bind(C, name="qk_param_atan")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_atan

    function qk_param_log(out, src) result(code) &
        bind(C, name="qk_param_log")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_log

    function qk_param_exp(out, src) result(code) &
        bind(C, name="qk_param_exp")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_exp

    function qk_param_abs(out, src) result(code) &
        bind(C, name="qk_param_abs")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_abs

    function qk_param_sign(out, src) result(code) &
        bind(C, name="qk_param_sign")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_sign

    function qk_param_neg(out, src) result(code) &
        bind(C, name="qk_param_neg")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_neg

    function qk_param_conjugate(out, src) result(code) &
        bind(C, name="qk_param_conjugate")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: out
      type(c_ptr), value, intent(in) :: src
      integer(c_int) :: code
    end function qk_param_conjugate

    function qk_param_equal(lhs, rhs) result(ptr) &
        bind(C, name="qk_param_equal")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: lhs
      type(c_ptr), value, intent(in) :: rhs
      type(c_ptr) :: ptr
    end function qk_param_equal

    function qk_param_as_real(param) result(ptr) &
        bind(C, name="qk_param_as_real")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: param
      type(c_ptr) :: ptr
    end function qk_param_as_real

    function qk_obs_zero(num_qubits) result(ptr) &
        bind(C, name="qk_obs_zero")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr) :: ptr
    end function qk_obs_zero

    function qk_obs_identity(num_qubits) result(ptr) &
        bind(C, name="qk_obs_identity")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr) :: ptr
    end function qk_obs_identity

    function qk_obs_new(num_qubits, num_terms, num_bits, coeffs, bit_terms, indices, boundaries) result(ptr) &
        bind(C, name="qk_obs_new")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: num_terms
      type(c_ptr), value, intent(in) :: num_bits
      type(c_ptr), value, intent(in) :: coeffs
      type(c_ptr), value, intent(in) :: bit_terms
      type(c_ptr), value, intent(in) :: indices
      type(c_ptr), value, intent(in) :: boundaries
      type(c_ptr) :: ptr
    end function qk_obs_new

    subroutine qk_obs_free(obs) &
        bind(C, name="qk_obs_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
    end subroutine qk_obs_free

    function qk_obs_add_term(obs, cterm) result(code) &
        bind(C, name="qk_obs_add_term")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr), value, intent(in) :: cterm
      integer(c_int) :: code
    end function qk_obs_add_term

    function qk_obs_term(obs, index, out) result(code) &
        bind(C, name="qk_obs_term")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr), value, intent(in) :: index
      type(c_ptr), value, intent(in) :: out
      integer(c_int) :: code
    end function qk_obs_term

    function qk_obs_num_terms(obs) result(n) &
        bind(C, name="qk_obs_num_terms")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: obs
      integer(c_size_t) :: n
    end function qk_obs_num_terms

    function qk_obs_num_qubits(obs) result(n) &
        bind(C, name="qk_obs_num_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: obs
      integer(c_int32_t) :: n
    end function qk_obs_num_qubits

    function qk_obs_len(obs) result(n) &
        bind(C, name="qk_obs_len")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: obs
      integer(c_size_t) :: n
    end function qk_obs_len

    function qk_obs_coeffs(obs) result(ptr) &
        bind(C, name="qk_obs_coeffs")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr) :: ptr
    end function qk_obs_coeffs

    function qk_obs_indices(obs) result(n) &
        bind(C, name="qk_obs_indices")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: obs
      integer(c_int32_t) :: n
    end function qk_obs_indices

    function qk_obs_boundaries(obs) result(n) &
        bind(C, name="qk_obs_boundaries")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: obs
      integer(c_size_t) :: n
    end function qk_obs_boundaries

    function qk_obs_bit_terms(obs) result(ptr) &
        bind(C, name="qk_obs_bit_terms")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr) :: ptr
    end function qk_obs_bit_terms

    function qk_obs_multiply(obs, coeff) result(ptr) &
        bind(C, name="qk_obs_multiply")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr), value, intent(in) :: coeff
      type(c_ptr) :: ptr
    end function qk_obs_multiply

    subroutine qk_obs_multiply_inplace(obs, coeff) &
        bind(C, name="qk_obs_multiply_inplace")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr), value, intent(in) :: coeff
    end subroutine qk_obs_multiply_inplace

    function qk_obs_add(left, right) result(ptr) &
        bind(C, name="qk_obs_add")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: left
      type(c_ptr), value, intent(in) :: right
      type(c_ptr) :: ptr
    end function qk_obs_add

    subroutine qk_obs_add_inplace(left, right) &
        bind(C, name="qk_obs_add_inplace")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: left
      type(c_ptr), value, intent(in) :: right
    end subroutine qk_obs_add_inplace

    function qk_obs_scaled_add(left, right, factor) result(ptr) &
        bind(C, name="qk_obs_scaled_add")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: left
      type(c_ptr), value, intent(in) :: right
      type(c_ptr), value, intent(in) :: factor
      type(c_ptr) :: ptr
    end function qk_obs_scaled_add

    subroutine qk_obs_scaled_add_inplace(left, right, factor) &
        bind(C, name="qk_obs_scaled_add_inplace")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: left
      type(c_ptr), value, intent(in) :: right
      type(c_ptr), value, intent(in) :: factor
    end subroutine qk_obs_scaled_add_inplace

    function qk_obs_compose(first, second) result(ptr) &
        bind(C, name="qk_obs_compose")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: first
      type(c_ptr), value, intent(in) :: second
      type(c_ptr) :: ptr
    end function qk_obs_compose

    function qk_obs_compose_map(first, second, qargs) result(ptr) &
        bind(C, name="qk_obs_compose_map")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: first
      type(c_ptr), value, intent(in) :: second
      integer(c_int32_t), value, intent(in) :: qargs
      type(c_ptr) :: ptr
    end function qk_obs_compose_map

    function qk_obs_apply_layout(obs, layout, num_qubits) result(code) &
        bind(C, name="qk_obs_apply_layout")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: obs
      integer(c_int32_t), value, intent(in) :: layout
      integer(c_int32_t), value, intent(in) :: num_qubits
      integer(c_int) :: code
    end function qk_obs_apply_layout

    function qk_obs_canonicalize(obs, tol) result(ptr) &
        bind(C, name="qk_obs_canonicalize")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr), value, intent(in) :: tol
      type(c_ptr) :: ptr
    end function qk_obs_canonicalize

    function qk_obs_copy(obs) result(ptr) &
        bind(C, name="qk_obs_copy")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr) :: ptr
    end function qk_obs_copy

    function qk_obs_equal(obs, other) result(ptr) &
        bind(C, name="qk_obs_equal")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr), value, intent(in) :: other
      type(c_ptr) :: ptr
    end function qk_obs_equal

    function qk_obs_str(obs) result(result) &
        bind(C, name="qk_obs_str")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: obs
      type(c_ptr) :: result
    end function qk_obs_str

    subroutine qk_str_free(string) &
        bind(C, name="qk_str_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: string
    end subroutine qk_str_free

    function qk_obsterm_str(term) result(result) &
        bind(C, name="qk_obsterm_str")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: term
      type(c_ptr) :: result
    end function qk_obsterm_str

    function qk_bitterm_label(bit_term) result(ptr) &
        bind(C, name="qk_bitterm_label")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: bit_term
      type(c_ptr) :: ptr
    end function qk_bitterm_label

    function qk_neighbors_is_all_to_all(neighbors) result(ptr) &
        bind(C, name="qk_neighbors_is_all_to_all")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: neighbors
      type(c_ptr) :: ptr
    end function qk_neighbors_is_all_to_all

    function qk_neighbors_from_target(target, neighbors) result(ptr) &
        bind(C, name="qk_neighbors_from_target")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: neighbors
      type(c_ptr) :: ptr
    end function qk_neighbors_from_target

    subroutine qk_neighbors_clear(neighbors) &
        bind(C, name="qk_neighbors_clear")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: neighbors
    end subroutine qk_neighbors_clear

    subroutine qk_transpiler_pass_standalone_basis_translator(circuit, target, min_qubits) &
        bind(C, name="qk_transpiler_pass_standalone_basis_translator")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: min_qubits
    end subroutine qk_transpiler_pass_standalone_basis_translator

    function qk_transpiler_pass_standalone_commutative_cancellation(circuit, target, approximation_degree) result(code) &
        bind(C, name="qk_transpiler_pass_standalone_commutative_cancellation")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: approximation_degree
      integer(c_int) :: code
    end function qk_transpiler_pass_standalone_commutative_cancellation

    subroutine qk_transpiler_pass_standalone_consolidate_blocks(circuit, target, approximation_degree, force_consolidate) &
        bind(C, name="qk_transpiler_pass_standalone_consolidate_blocks")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: approximation_degree
      type(c_ptr), value, intent(in) :: force_consolidate
    end subroutine qk_transpiler_pass_standalone_consolidate_blocks

    subroutine qk_transpiler_pass_standalone_convert_to_pauli_rotations(circuit) &
        bind(C, name="qk_transpiler_pass_standalone_convert_to_pauli_rotations")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
    end subroutine qk_transpiler_pass_standalone_convert_to_pauli_rotations

    function qk_transpiler_pass_standalone_elide_permutations(circuit) result(ptr) &
        bind(C, name="qk_transpiler_pass_standalone_elide_permutations")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_standalone_elide_permutations

    function qk_transpiler_pass_elide_permutations(dag) result(ptr) &
        bind(C, name="qk_transpiler_pass_elide_permutations")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_elide_permutations

    function qk_transpiler_pass_standalone_check_gate_direction(circuit, target) result(ptr) &
        bind(C, name="qk_transpiler_pass_standalone_check_gate_direction")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_standalone_check_gate_direction

    subroutine qk_transpiler_pass_standalone_gate_direction(circuit, target) &
        bind(C, name="qk_transpiler_pass_standalone_gate_direction")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
    end subroutine qk_transpiler_pass_standalone_gate_direction

    function qk_transpiler_pass_check_gate_direction(dag, target) result(ptr) &
        bind(C, name="qk_transpiler_pass_check_gate_direction")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_check_gate_direction

    subroutine qk_transpiler_pass_gate_direction(dag, target) &
        bind(C, name="qk_transpiler_pass_gate_direction")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
    end subroutine qk_transpiler_pass_gate_direction

    subroutine qk_transpiler_pass_standalone_inverse_cancellation(circuit) &
        bind(C, name="qk_transpiler_pass_standalone_inverse_cancellation")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
    end subroutine qk_transpiler_pass_standalone_inverse_cancellation

    subroutine qk_transpiler_pass_standalone_litinski_transformation(circuit, fix_clifford) &
        bind(C, name="qk_transpiler_pass_standalone_litinski_transformation")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: fix_clifford
    end subroutine qk_transpiler_pass_standalone_litinski_transformation

    subroutine qk_transpiler_standalone_optimize_1q_sequences(circuit, target) &
        bind(C, name="qk_transpiler_standalone_optimize_1q_sequences")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
    end subroutine qk_transpiler_standalone_optimize_1q_sequences

    subroutine qk_transpiler_pass_standalone_optimize_1q_sequences(circuit, target) &
        bind(C, name="qk_transpiler_pass_standalone_optimize_1q_sequences")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
    end subroutine qk_transpiler_pass_standalone_optimize_1q_sequences

    subroutine qk_transpiler_pass_optimize_1q_sequences(dag, target) &
        bind(C, name="qk_transpiler_pass_optimize_1q_sequences")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
    end subroutine qk_transpiler_pass_optimize_1q_sequences

    subroutine qk_transpiler_pass_standalone_remove_diagonal_gates_befor1RUDHG(circuit) &
        bind(C, name="qk_transpiler_pass_standalone_remove_diagonal_gates_befor1RUDHG")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
    end subroutine qk_transpiler_pass_standalone_remove_diagonal_gates_befor1RUDHG

    subroutine qk_transpiler_pass_remove_diagonal_gates_before_measure(dag) &
        bind(C, name="qk_transpiler_pass_remove_diagonal_gates_before_measure")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
    end subroutine qk_transpiler_pass_remove_diagonal_gates_before_measure

    subroutine qk_transpiler_pass_standalone_remove_identity_equivalent(circuit, target, approximation_degree) &
        bind(C, name="qk_transpiler_pass_standalone_remove_identity_equivalent")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: approximation_degree
    end subroutine qk_transpiler_pass_standalone_remove_identity_equivalent

    subroutine qk_transpiler_pass_remove_identity_equivalent(dag, target, approximation_degree) &
        bind(C, name="qk_transpiler_pass_remove_identity_equivalent")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: approximation_degree
    end subroutine qk_transpiler_pass_remove_identity_equivalent

    function qk_sabre_layout_options_default() result(ptr) &
        bind(C, name="qk_sabre_layout_options_default")
      import :: c_ptr
      type(c_ptr) :: ptr
    end function qk_sabre_layout_options_default

    function qk_transpiler_pass_standalone_sabre_layout(circuit, target, options) result(ptr) &
        bind(C, name="qk_transpiler_pass_standalone_sabre_layout")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: options
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_standalone_sabre_layout

    function qk_transpiler_pass_standalone_split_2q_unitaries(circuit, requested_fidelity, split_swaps) result(ptr) &
        bind(C, name="qk_transpiler_pass_standalone_split_2q_unitaries")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: requested_fidelity
      type(c_ptr), value, intent(in) :: split_swaps
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_standalone_split_2q_unitaries

    function qk_transpiler_pass_split_2q_unitaries(dag, requested_fidelity, split_swaps) result(ptr) &
        bind(C, name="qk_transpiler_pass_split_2q_unitaries")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: requested_fidelity
      type(c_ptr), value, intent(in) :: split_swaps
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_split_2q_unitaries

    subroutine qk_transpiler_pass_standalone_unitary_synthesis(circuit, target, min_qubits, approximation_degree) &
        bind(C, name="qk_transpiler_pass_standalone_unitary_synthesis")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: min_qubits
      type(c_ptr), value, intent(in) :: approximation_degree
    end subroutine qk_transpiler_pass_standalone_unitary_synthesis

    function qk_vf2_layout_result_has_match(layout) result(ptr) &
        bind(C, name="qk_vf2_layout_result_has_match")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: layout
      type(c_ptr) :: ptr
    end function qk_vf2_layout_result_has_match

    function qk_vf2_layout_result_has_improvement(layout) result(ptr) &
        bind(C, name="qk_vf2_layout_result_has_improvement")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: layout
      type(c_ptr) :: ptr
    end function qk_vf2_layout_result_has_improvement

    function qk_vf2_layout_result_map_virtual_qubit(layout, qubit) result(n) &
        bind(C, name="qk_vf2_layout_result_map_virtual_qubit")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: layout
      integer(c_int32_t), value, intent(in) :: qubit
      integer(c_int32_t) :: n
    end function qk_vf2_layout_result_map_virtual_qubit

    subroutine qk_vf2_layout_result_free(layout) &
        bind(C, name="qk_vf2_layout_result_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: layout
    end subroutine qk_vf2_layout_result_free

    function qk_vf2_layout_configuration_new() result(ptr) &
        bind(C, name="qk_vf2_layout_configuration_new")
      import :: c_ptr
      type(c_ptr) :: ptr
    end function qk_vf2_layout_configuration_new

    subroutine qk_vf2_layout_configuration_free(config) &
        bind(C, name="qk_vf2_layout_configuration_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: config
    end subroutine qk_vf2_layout_configuration_free

    subroutine qk_vf2_layout_configuration_set_call_limit(config, before, after) &
        bind(C, name="qk_vf2_layout_configuration_set_call_limit")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: config
      type(c_ptr), value, intent(in) :: before
      type(c_ptr), value, intent(in) :: after
    end subroutine qk_vf2_layout_configuration_set_call_limit

    subroutine qk_vf2_layout_configuration_set_time_limit(config, limit) &
        bind(C, name="qk_vf2_layout_configuration_set_time_limit")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: config
      type(c_ptr), value, intent(in) :: limit
    end subroutine qk_vf2_layout_configuration_set_time_limit

    subroutine qk_vf2_layout_configuration_set_max_trials(config, limit) &
        bind(C, name="qk_vf2_layout_configuration_set_max_trials")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: config
      type(c_ptr), value, intent(in) :: limit
    end subroutine qk_vf2_layout_configuration_set_max_trials

    subroutine qk_vf2_layout_configuration_set_shuffle_seed(config, seed) &
        bind(C, name="qk_vf2_layout_configuration_set_shuffle_seed")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: config
      integer(c_int32_t), value, intent(in) :: seed
    end subroutine qk_vf2_layout_configuration_set_shuffle_seed

    subroutine qk_vf2_layout_configuration_set_score_initial(config, score_initial) &
        bind(C, name="qk_vf2_layout_configuration_set_score_initial")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: config
      type(c_ptr), value, intent(in) :: score_initial
    end subroutine qk_vf2_layout_configuration_set_score_initial

    function qk_transpiler_pass_standalone_vf2_layout_average(circuit, target, config, strict_direction) result(ptr) &
        bind(C, name="qk_transpiler_pass_standalone_vf2_layout_average")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: config
      type(c_ptr), value, intent(in) :: strict_direction
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_standalone_vf2_layout_average

    function qk_transpiler_pass_standalone_vf2_layout_exact(circuit, target, config) result(ptr) &
        bind(C, name="qk_transpiler_pass_standalone_vf2_layout_exact")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: config
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_standalone_vf2_layout_exact

    function qk_transpiler_pass_standalone_vf2_layout(&
        circuit, &
        target, &
        strict_direction, &
        call_limit, &
        time_limit, &
        max_trials) result(ptr) &
        bind(C, name="qk_transpiler_pass_standalone_vf2_layout")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: circuit
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: strict_direction
      type(c_ptr), value, intent(in) :: call_limit
      type(c_ptr), value, intent(in) :: time_limit
      type(c_ptr), value, intent(in) :: max_trials
      type(c_ptr) :: ptr
    end function qk_transpiler_pass_standalone_vf2_layout

    function qk_target_new(num_qubits) result(ptr) &
        bind(C, name="qk_target_new")
      import :: c_ptr, c_int32_t
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr) :: ptr
    end function qk_target_new

    function qk_target_num_qubits(target) result(n) &
        bind(C, name="qk_target_num_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t) :: n
    end function qk_target_num_qubits

    function qk_target_dt(target) result(ptr) &
        bind(C, name="qk_target_dt")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: target
      type(c_ptr) :: ptr
    end function qk_target_dt

    function qk_target_granularity(target) result(n) &
        bind(C, name="qk_target_granularity")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t) :: n
    end function qk_target_granularity

    function qk_target_min_length(target) result(n) &
        bind(C, name="qk_target_min_length")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t) :: n
    end function qk_target_min_length

    function qk_target_pulse_alignment(target) result(n) &
        bind(C, name="qk_target_pulse_alignment")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t) :: n
    end function qk_target_pulse_alignment

    function qk_target_acquire_alignment(target) result(n) &
        bind(C, name="qk_target_acquire_alignment")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t) :: n
    end function qk_target_acquire_alignment

    function qk_target_set_dt(target, dt) result(code) &
        bind(C, name="qk_target_set_dt")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: dt
      integer(c_int) :: code
    end function qk_target_set_dt

    function qk_target_set_granularity(target, granularity) result(code) &
        bind(C, name="qk_target_set_granularity")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t), value, intent(in) :: granularity
      integer(c_int) :: code
    end function qk_target_set_granularity

    function qk_target_set_min_length(target, min_length) result(code) &
        bind(C, name="qk_target_set_min_length")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t), value, intent(in) :: min_length
      integer(c_int) :: code
    end function qk_target_set_min_length

    function qk_target_set_pulse_alignment(target, pulse_alignment) result(code) &
        bind(C, name="qk_target_set_pulse_alignment")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t), value, intent(in) :: pulse_alignment
      integer(c_int) :: code
    end function qk_target_set_pulse_alignment

    function qk_target_set_acquire_alignment(target, acquire_alignment) result(code) &
        bind(C, name="qk_target_set_acquire_alignment")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t), value, intent(in) :: acquire_alignment
      integer(c_int) :: code
    end function qk_target_set_acquire_alignment

    function qk_target_copy(target) result(ptr) &
        bind(C, name="qk_target_copy")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: target
      type(c_ptr) :: ptr
    end function qk_target_copy

    subroutine qk_target_free(target) &
        bind(C, name="qk_target_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: target
    end subroutine qk_target_free

    function qk_target_entry_new(operation) result(ptr) &
        bind(C, name="qk_target_entry_new")
      import :: c_ptr, c_int
      integer(c_int), value, intent(in) :: operation
      type(c_ptr) :: ptr
    end function qk_target_entry_new

    function qk_target_entry_new_measure() result(ptr) &
        bind(C, name="qk_target_entry_new_measure")
      import :: c_ptr
      type(c_ptr) :: ptr
    end function qk_target_entry_new_measure

    function qk_target_entry_new_reset() result(ptr) &
        bind(C, name="qk_target_entry_new_reset")
      import :: c_ptr
      type(c_ptr) :: ptr
    end function qk_target_entry_new_reset

    function qk_target_entry_new_fixed(operation, params, name) result(ptr) &
        bind(C, name="qk_target_entry_new_fixed")
      import :: c_ptr, c_int
      integer(c_int), value, intent(in) :: operation
      type(c_ptr), value, intent(in) :: params
      type(c_ptr), value, intent(in) :: name
      type(c_ptr) :: ptr
    end function qk_target_entry_new_fixed

    function qk_target_entry_num_properties(entry) result(n) &
        bind(C, name="qk_target_entry_num_properties")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: entry
      integer(c_size_t) :: n
    end function qk_target_entry_num_properties

    subroutine qk_target_entry_free(entry) &
        bind(C, name="qk_target_entry_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: entry
    end subroutine qk_target_entry_free

    function qk_target_entry_add_property(entry, qargs, num_qubits, duration, error) result(code) &
        bind(C, name="qk_target_entry_add_property")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: entry
      type(c_ptr), value, intent(in) :: qargs
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: duration
      type(c_ptr), value, intent(in) :: error
      integer(c_int) :: code
    end function qk_target_entry_add_property

    function qk_target_entry_set_name(entry, name) result(code) &
        bind(C, name="qk_target_entry_set_name")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: entry
      type(c_ptr), value, intent(in) :: name
      integer(c_int) :: code
    end function qk_target_entry_set_name

    function qk_target_add_instruction(target, target_entry) result(code) &
        bind(C, name="qk_target_add_instruction")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: target_entry
      integer(c_int) :: code
    end function qk_target_add_instruction

    function qk_target_update_property(target, instruction, qargs, num_qubits, duration, error) result(code) &
        bind(C, name="qk_target_update_property")
      import :: c_ptr, c_int, c_int32_t
      type(c_ptr), value, intent(in) :: target
      integer(c_int), value, intent(in) :: instruction
      type(c_ptr), value, intent(in) :: qargs
      integer(c_int32_t), value, intent(in) :: num_qubits
      type(c_ptr), value, intent(in) :: duration
      type(c_ptr), value, intent(in) :: error
      integer(c_int) :: code
    end function qk_target_update_property

    function qk_target_num_instructions(target) result(n) &
        bind(C, name="qk_target_num_instructions")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: target
      integer(c_size_t) :: n
    end function qk_target_num_instructions

    function qk_target_instruction_supported(target, operation_name, qargs, params) result(ptr) &
        bind(C, name="qk_target_instruction_supported")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: operation_name
      integer(c_int32_t), value, intent(in) :: qargs
      type(c_ptr), value, intent(in) :: params
      type(c_ptr) :: ptr
    end function qk_target_instruction_supported

    function qk_target_op_index(target, name) result(n) &
        bind(C, name="qk_target_op_index")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: name
      integer(c_size_t) :: n
    end function qk_target_op_index

    function qk_target_op_name(target, index) result(result) &
        bind(C, name="qk_target_op_name")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: index
      type(c_ptr) :: result
    end function qk_target_op_name

    function qk_target_op_num_properties(target, index) result(n) &
        bind(C, name="qk_target_op_num_properties")
      import :: c_ptr, c_size_t
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: index
      integer(c_size_t) :: n
    end function qk_target_op_num_properties

    function qk_target_op_qargs_index(target, op_idx, qargs) result(n) &
        bind(C, name="qk_target_op_qargs_index")
      import :: c_ptr, c_int32_t, c_size_t
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: op_idx
      integer(c_int32_t), value, intent(in) :: qargs
      integer(c_size_t) :: n
    end function qk_target_op_qargs_index

    subroutine qk_target_op_qargs(target, op_idx, qarg_idx, qargs_out, qargs_len) &
        bind(C, name="qk_target_op_qargs")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: op_idx
      type(c_ptr), value, intent(in) :: qarg_idx
      type(c_ptr), value, intent(in) :: qargs_out
      integer(c_int32_t), value, intent(in) :: qargs_len
    end subroutine qk_target_op_qargs

    subroutine qk_target_op_props(target, op_idx, qarg_idx, inst_props) &
        bind(C, name="qk_target_op_props")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: op_idx
      type(c_ptr), value, intent(in) :: qarg_idx
      type(c_ptr), value, intent(in) :: inst_props
    end subroutine qk_target_op_props

    subroutine qk_target_op_get(target, index, out_op) &
        bind(C, name="qk_target_op_get")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: index
      type(c_ptr), value, intent(in) :: out_op
    end subroutine qk_target_op_get

    function qk_target_op_gate(target, index) result(code) &
        bind(C, name="qk_target_op_gate")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: index
      integer(c_int) :: code
    end function qk_target_op_gate

    subroutine qk_target_op_clear(op) &
        bind(C, name="qk_target_op_clear")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: op
    end subroutine qk_target_op_clear

    subroutine qk_transpile_state_new(state) &
        bind(C, name="qk_transpile_state_new")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: state
    end subroutine qk_transpile_state_new

    subroutine qk_transpile_state_free(state) &
        bind(C, name="qk_transpile_state_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: state
    end subroutine qk_transpile_state_free

    function qk_transpile_state_layout(state) result(ptr) &
        bind(C, name="qk_transpile_state_layout")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: state
      type(c_ptr) :: ptr
    end function qk_transpile_state_layout

    subroutine qk_transpile_state_layout_set(state, layout) &
        bind(C, name="qk_transpile_state_layout_set")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: state
      type(c_ptr), value, intent(in) :: layout
    end subroutine qk_transpile_state_layout_set

    function qk_transpiler_default_options() result(ptr) &
        bind(C, name="qk_transpiler_default_options")
      import :: c_ptr
      type(c_ptr) :: ptr
    end function qk_transpiler_default_options

    function qk_transpile_stage_init(dag, target, options, state, error) result(code) &
        bind(C, name="qk_transpile_stage_init")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: options
      type(c_ptr), value, intent(in) :: state
      type(c_ptr), value, intent(in) :: error
      integer(c_int) :: code
    end function qk_transpile_stage_init

    function qk_transpile_stage_routing(dag, target, options, state, error) result(code) &
        bind(C, name="qk_transpile_stage_routing")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: options
      type(c_ptr), value, intent(in) :: state
      type(c_ptr), value, intent(in) :: error
      integer(c_int) :: code
    end function qk_transpile_stage_routing

    function qk_transpile_stage_optimization(dag, target, options, error, state) result(code) &
        bind(C, name="qk_transpile_stage_optimization")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: options
      type(c_ptr), value, intent(in) :: error
      type(c_ptr), value, intent(in) :: state
      integer(c_int) :: code
    end function qk_transpile_stage_optimization

    function qk_transpile_stage_translation(dag, target, options, error) result(code) &
        bind(C, name="qk_transpile_stage_translation")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: options
      type(c_ptr), value, intent(in) :: error
      integer(c_int) :: code
    end function qk_transpile_stage_translation

    function qk_transpile_stage_layout(dag, target, options, state, error) result(code) &
        bind(C, name="qk_transpile_stage_layout")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: dag
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: options
      type(c_ptr), value, intent(in) :: state
      type(c_ptr), value, intent(in) :: error
      integer(c_int) :: code
    end function qk_transpile_stage_layout

    function qk_transpile(qc, target, options, result, error) result(code) &
        bind(C, name="qk_transpile")
      import :: c_ptr, c_int
      type(c_ptr), value, intent(in) :: qc
      type(c_ptr), value, intent(in) :: target
      type(c_ptr), value, intent(in) :: options
      type(c_ptr), value, intent(in) :: result
      type(c_ptr), value, intent(in) :: error
      integer(c_int) :: code
    end function qk_transpile

    function qk_transpile_layout_num_input_qubits(layout) result(n) &
        bind(C, name="qk_transpile_layout_num_input_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: layout
      integer(c_int32_t) :: n
    end function qk_transpile_layout_num_input_qubits

    function qk_transpile_layout_num_output_qubits(layout) result(n) &
        bind(C, name="qk_transpile_layout_num_output_qubits")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: layout
      integer(c_int32_t) :: n
    end function qk_transpile_layout_num_output_qubits

    function qk_transpile_layout_initial_layout(layout, filter_ancillas, initial_layout) result(ptr) &
        bind(C, name="qk_transpile_layout_initial_layout")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: layout
      type(c_ptr), value, intent(in) :: filter_ancillas
      integer(c_int32_t), value, intent(in) :: initial_layout
      type(c_ptr) :: ptr
    end function qk_transpile_layout_initial_layout

    function qk_transpile_layout_output_permutation(layout, output_permutation) result(ptr) &
        bind(C, name="qk_transpile_layout_output_permutation")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: layout
      integer(c_int32_t), value, intent(in) :: output_permutation
      type(c_ptr) :: ptr
    end function qk_transpile_layout_output_permutation

    subroutine qk_transpile_layout_final_layout(layout, filter_ancillas, final_layout) &
        bind(C, name="qk_transpile_layout_final_layout")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: layout
      type(c_ptr), value, intent(in) :: filter_ancillas
      integer(c_int32_t), value, intent(in) :: final_layout
    end subroutine qk_transpile_layout_final_layout

    function qk_transpile_layout_generate_from_mapping(original_dag, target, qubit_mapping) result(ptr) &
        bind(C, name="qk_transpile_layout_generate_from_mapping")
      import :: c_ptr, c_int32_t
      type(c_ptr), value, intent(in) :: original_dag
      type(c_ptr), value, intent(in) :: target
      integer(c_int32_t), value, intent(in) :: qubit_mapping
      type(c_ptr) :: ptr
    end function qk_transpile_layout_generate_from_mapping

    subroutine qk_transpile_layout_free(layout) &
        bind(C, name="qk_transpile_layout_free")
      import :: c_ptr
      type(c_ptr), value, intent(in) :: layout
    end subroutine qk_transpile_layout_free

  end interface

end module qiskit_c_api
