! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module qiskit_swigf
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 ! struct QkComplex64
 type, bind(C), public :: QkComplex64
  real(C_DOUBLE), public :: re
  real(C_DOUBLE), public :: im
 end type QkComplex64
 ! enum QkExitCode
 enum, bind(c)
  enumerator :: QkExitCode_Success = 0
  enumerator :: QkExitCode_CInputError = 100
  enumerator :: QkExitCode_NullPointerError = 101
  enumerator :: QkExitCode_AlignmentError = 102
  enumerator :: QkExitCode_IndexError = 103
  enumerator :: QkExitCode_DuplicateIndexError = 104
  enumerator :: QkExitCode_InvalidOperationKind = 105
  enumerator :: QkExitCode_ArithmeticError = 200
  enumerator :: QkExitCode_MismatchedQubits = 201
  enumerator :: QkExitCode_ExpectedUnitary = 202
  enumerator :: QkExitCode_TargetError = 300
  enumerator :: QkExitCode_TargetInstAlreadyExists = 301
  enumerator :: QkExitCode_TargetQargMismatch = 302
  enumerator :: QkExitCode_TargetInvalidQargsKey = 303
  enumerator :: QkExitCode_TargetInvalidInstKey = 304
  enumerator :: QkExitCode_TranspilerError = 400
  enumerator :: QkExitCode_DagError = 500
  enumerator :: QkExitCode_DagComposeMismatch = 501
  enumerator :: QkExitCode_DagComposeMissingBit = 502
  enumerator :: QkExitCode_ParameterError = 600
  enumerator :: QkExitCode_ParameterNameConflict = 601
 end enum
 integer, parameter, public :: QkExitCode = kind(QkExitCode_Success)
 public :: QkExitCode_Success, QkExitCode_CInputError, QkExitCode_NullPointerError, QkExitCode_AlignmentError, &
    QkExitCode_IndexError, QkExitCode_DuplicateIndexError, QkExitCode_InvalidOperationKind, QkExitCode_ArithmeticError, &
    QkExitCode_MismatchedQubits, QkExitCode_ExpectedUnitary, QkExitCode_TargetError, QkExitCode_TargetInstAlreadyExists, &
    QkExitCode_TargetQargMismatch, QkExitCode_TargetInvalidQargsKey, QkExitCode_TargetInvalidInstKey, &
    QkExitCode_TranspilerError, QkExitCode_DagError, QkExitCode_DagComposeMismatch, QkExitCode_DagComposeMissingBit, &
    QkExitCode_ParameterError, QkExitCode_ParameterNameConflict
 ! enum QkGate
 enum, bind(c)
  enumerator :: QkGate_GlobalPhase = 0
  enumerator :: QkGate_H = 1
  enumerator :: QkGate_I = 2
  enumerator :: QkGate_X = 3
  enumerator :: QkGate_Y = 4
  enumerator :: QkGate_Z = 5
  enumerator :: QkGate_Phase = 6
  enumerator :: QkGate_R = 7
  enumerator :: QkGate_RX = 8
  enumerator :: QkGate_RY = 9
  enumerator :: QkGate_RZ = 10
  enumerator :: QkGate_S = 11
  enumerator :: QkGate_Sdg = 12
  enumerator :: QkGate_SX = 13
  enumerator :: QkGate_SXdg = 14
  enumerator :: QkGate_T = 15
  enumerator :: QkGate_Tdg = 16
  enumerator :: QkGate_U = 17
  enumerator :: QkGate_U1 = 18
  enumerator :: QkGate_U2 = 19
  enumerator :: QkGate_U3 = 20
  enumerator :: QkGate_CH = 21
  enumerator :: QkGate_CX = 22
  enumerator :: QkGate_CY = 23
  enumerator :: QkGate_CZ = 24
  enumerator :: QkGate_DCX = 25
  enumerator :: QkGate_ECR = 26
  enumerator :: QkGate_Swap = 27
  enumerator :: QkGate_ISwap = 28
  enumerator :: QkGate_CPhase = 29
  enumerator :: QkGate_CRX = 30
  enumerator :: QkGate_CRY = 31
  enumerator :: QkGate_CRZ = 32
  enumerator :: QkGate_CS = 33
  enumerator :: QkGate_CSdg = 34
  enumerator :: QkGate_CSX = 35
  enumerator :: QkGate_CU = 36
  enumerator :: QkGate_CU1 = 37
  enumerator :: QkGate_CU3 = 38
  enumerator :: QkGate_RXX = 39
  enumerator :: QkGate_RYY = 40
  enumerator :: QkGate_RZZ = 41
  enumerator :: QkGate_RZX = 42
  enumerator :: QkGate_XXMinusYY = 43
  enumerator :: QkGate_XXPlusYY = 44
  enumerator :: QkGate_CCX = 45
  enumerator :: QkGate_CCZ = 46
  enumerator :: QkGate_CSwap = 47
  enumerator :: QkGate_RCCX = 48
  enumerator :: QkGate_C3X = 49
  enumerator :: QkGate_C3SX = 50
  enumerator :: QkGate_RC3X = 51
 end enum
 integer, parameter, public :: QkGate = kind(QkGate_GlobalPhase)
 public :: QkGate_GlobalPhase, QkGate_H, QkGate_I, QkGate_X, QkGate_Y, QkGate_Z, QkGate_Phase, QkGate_R, QkGate_RX, QkGate_RY, &
    QkGate_RZ, QkGate_S, QkGate_Sdg, QkGate_SX, QkGate_SXdg, QkGate_T, QkGate_Tdg, QkGate_U, QkGate_U1, QkGate_U2, QkGate_U3, &
    QkGate_CH, QkGate_CX, QkGate_CY, QkGate_CZ, QkGate_DCX, QkGate_ECR, QkGate_Swap, QkGate_ISwap, QkGate_CPhase, QkGate_CRX, &
    QkGate_CRY, QkGate_CRZ, QkGate_CS, QkGate_CSdg, QkGate_CSX, QkGate_CU, QkGate_CU1, QkGate_CU3, QkGate_RXX, QkGate_RYY, &
    QkGate_RZZ, QkGate_RZX, QkGate_XXMinusYY, QkGate_XXPlusYY, QkGate_CCX, QkGate_CCZ, QkGate_CSwap, QkGate_RCCX, QkGate_C3X, &
    QkGate_C3SX, QkGate_RC3X
 ! enum QkOperationKind
 enum, bind(c)
  enumerator :: QkOperationKind_Gate = 0
  enumerator :: QkOperationKind_Barrier = 1
  enumerator :: QkOperationKind_Delay = 2
  enumerator :: QkOperationKind_Measure = 3
  enumerator :: QkOperationKind_Reset = 4
  enumerator :: QkOperationKind_Unitary = 5
  enumerator :: QkOperationKind_PauliProductMeasurement = 6
  enumerator :: QkOperationKind_ControlFlow = 7
  enumerator :: QkOperationKind_Unknown = 8
  enumerator :: QkOperationKind_PauliProductRotation = 9
 end enum
 integer, parameter, public :: QkOperationKind = kind(QkOperationKind_Gate)
 public :: QkOperationKind_Gate, QkOperationKind_Barrier, QkOperationKind_Delay, QkOperationKind_Measure, &
    QkOperationKind_Reset, QkOperationKind_Unitary, QkOperationKind_PauliProductMeasurement, QkOperationKind_ControlFlow, &
    QkOperationKind_Unknown, QkOperationKind_PauliProductRotation
 ! enum QkDelayUnit
 enum, bind(c)
  enumerator :: QkDelayUnit_S = 0
  enumerator :: QkDelayUnit_MS = 1
  enumerator :: QkDelayUnit_US = 2
  enumerator :: QkDelayUnit_NS = 3
  enumerator :: QkDelayUnit_PS = 4
 end enum
 integer, parameter, public :: QkDelayUnit = kind(QkDelayUnit_S)
 public :: QkDelayUnit_S, QkDelayUnit_MS, QkDelayUnit_US, QkDelayUnit_NS, QkDelayUnit_PS
 ! enum QkVarsMode
 enum, bind(c)
  enumerator :: QkVarsMode_Alike = 0
  enumerator :: QkVarsMode_Captures = 1
  enumerator :: QkVarsMode_Drop = 2
 end enum
 integer, parameter, public :: QkVarsMode = kind(QkVarsMode_Alike)
 public :: QkVarsMode_Alike, QkVarsMode_Captures, QkVarsMode_Drop
 ! enum QkBlocksMode
 enum, bind(c)
  enumerator :: QkBlocksMode_Drop = 0
  enumerator :: QkBlocksMode_Keep = 1
 end enum
 integer, parameter, public :: QkBlocksMode = kind(QkBlocksMode_Drop)
 public :: QkBlocksMode_Drop, QkBlocksMode_Keep
 ! enum QkDagNodeType
 enum, bind(c)
  enumerator :: QkDagNodeType_Operation = 0
  enumerator :: QkDagNodeType_QubitIn = 1
  enumerator :: QkDagNodeType_QubitOut = 2
  enumerator :: QkDagNodeType_ClbitIn = 3
  enumerator :: QkDagNodeType_ClbitOut = 4
  enumerator :: QkDagNodeType_VarIn = 5
  enumerator :: QkDagNodeType_VarOut = 6
 end enum
 integer, parameter, public :: QkDagNodeType = kind(QkDagNodeType_Operation)
 public :: QkDagNodeType_Operation, QkDagNodeType_QubitIn, QkDagNodeType_QubitOut, QkDagNodeType_ClbitIn, &
    QkDagNodeType_ClbitOut, QkDagNodeType_VarIn, QkDagNodeType_VarOut
 ! enum QkBitTerm
 enum, bind(c)
  enumerator :: QkBitTerm_X = 2
  enumerator :: QkBitTerm_Plus = 10
  enumerator :: QkBitTerm_Minus = 6
  enumerator :: QkBitTerm_Y = 3
  enumerator :: QkBitTerm_Right = 11
  enumerator :: QkBitTerm_Left = 7
  enumerator :: QkBitTerm_Z = 1
  enumerator :: QkBitTerm_Zero = 9
  enumerator :: QkBitTerm_One = 5
 end enum
 integer, parameter, public :: QkBitTerm = kind(QkBitTerm_X)
 public :: QkBitTerm_X, QkBitTerm_Plus, QkBitTerm_Minus, QkBitTerm_Y, QkBitTerm_Right, QkBitTerm_Left, QkBitTerm_Z, &
    QkBitTerm_Zero, QkBitTerm_One
 ! struct QkOpCount
 type, bind(C), public :: QkOpCount
  type(C_PTR), public :: name
  integer(C_SIZE_T), public :: count
 end type QkOpCount
 ! struct QkOpCounts
 type, bind(C), public :: QkOpCounts
  type(C_PTR), public :: data
  integer(C_SIZE_T), public :: len
 end type QkOpCounts
 ! struct QkCircuitInstruction
 type, bind(C), public :: QkCircuitInstruction
  type(C_PTR), public :: name
  type(C_PTR), public :: qubits
  type(C_PTR), public :: clbits
  type(C_PTR), public :: params
  integer(C_INT32_T), public :: num_qubits
  integer(C_INT32_T), public :: num_clbits
  integer(C_INT32_T), public :: num_params
 end type QkCircuitInstruction
 ! struct QkPauliProductRotation
 type, bind(C), public :: QkPauliProductRotation
  type(C_PTR), public :: z
  type(C_PTR), public :: x
  integer(C_SIZE_T), public :: len
  type(C_PTR), public :: angle
 end type QkPauliProductRotation
 ! struct QkPauliProductMeasurement
 type, bind(C), public :: QkPauliProductMeasurement
  type(C_PTR), public :: z
  type(C_PTR), public :: x
  integer(C_SIZE_T), public :: len
  logical(C_BOOL), public :: flip_outcome
 end type QkPauliProductMeasurement
 ! struct QkCircuitDrawerConfig
 type, bind(C), public :: QkCircuitDrawerConfig
  logical(C_BOOL), public :: bundle_cregs
  logical(C_BOOL), public :: merge_wires
  integer(C_SIZE_T), public :: fold
 end type QkCircuitDrawerConfig
 ! struct QkDagNeighbors
 type, bind(C), public :: QkDagNeighbors
  type(C_PTR), public :: neighbors
  integer(C_SIZE_T), public :: num_neighbors
 end type QkDagNeighbors
 ! struct QkObsTerm
 type, bind(C), public :: QkObsTerm
  type(QkComplex64), public :: coeff
  integer(C_SIZE_T), public :: len
  type(C_PTR), public :: bit_terms
  type(C_PTR), public :: indices
  integer(C_INT32_T), public :: num_qubits
 end type QkObsTerm
 ! struct QkNeighbors
 type, bind(C), public :: QkNeighbors
  type(C_PTR), public :: neighbors
  type(C_PTR), public :: partition
  integer(C_INT32_T), public :: num_qubits
 end type QkNeighbors
 ! struct QkSabreLayoutOptions
 type, bind(C), public :: QkSabreLayoutOptions
  integer(C_SIZE_T), public :: max_iterations
  integer(C_SIZE_T), public :: num_swap_trials
  integer(C_SIZE_T), public :: num_random_trials
  integer(C_INT64_T), public :: seed
 end type QkSabreLayoutOptions
 ! struct QkInstructionProperties
 type, bind(C), public :: QkInstructionProperties
  real(C_DOUBLE), public :: duration
  real(C_DOUBLE), public :: error
 end type QkInstructionProperties
 ! struct QkTargetOp
 type, bind(C), public :: QkTargetOp
  integer(C_INT), public :: op_type
  type(C_PTR), public :: name
  integer(C_INT32_T), public :: num_qubits
  type(C_PTR), public :: params
  integer(C_INT32_T), public :: num_params
 end type QkTargetOp
 ! struct QkTranspileOptions
 type, bind(C), public :: QkTranspileOptions
  integer(C_INT8_T), public :: optimization_level
  integer(C_INT64_T), public :: seed
  real(C_DOUBLE), public :: approximation_degree
 end type QkTranspileOptions
 ! struct QkTranspileResult
 type, bind(C), public :: QkTranspileResult
  type(C_PTR), public :: circuit
  type(C_PTR), public :: layout
 end type QkTranspileResult
 public :: qk_api_version
 public :: qk_circuit_new
 public :: qk_quantum_register_new
 public :: qk_quantum_register_free
 public :: qk_classical_register_free
 public :: qk_classical_register_new
 public :: qk_circuit_add_quantum_register
 public :: qk_circuit_add_classical_register
 public :: qk_circuit_copy
 public :: qk_circuit_num_qubits
 public :: qk_circuit_num_clbits
 public :: qk_circuit_num_param_symbols
 public :: qk_circuit_free
 public :: qk_circuit_gate
 public :: qk_circuit_parameterized_gate
 public :: qk_gate_num_qubits
 public :: qk_gate_num_params
 public :: qk_circuit_measure
 public :: qk_circuit_reset
 public :: qk_circuit_barrier
 public :: qk_circuit_unitary
 public :: qk_circuit_inst_unitary
 public :: qk_circuit_instruction_kind
 public :: qk_circuit_count_ops
 public :: qk_circuit_num_instructions
 public :: qk_circuit_get_instruction
 public :: qk_circuit_pauli_product_rotation
 public :: qk_circuit_inst_pauli_product_rotation
 public :: qk_circuit_pauli_product_measurement
 public :: qk_circuit_inst_pauli_product_measurement
 public :: qk_circuit_instruction_clear
 public :: qk_opcounts_clear
 public :: qk_circuit_delay
 public :: qk_circuit_draw
 public :: qk_circuit_to_dag
 public :: qk_circuit_copy_empty_like
 public :: qk_circuit_library_iqp
 public :: qk_circuit_library_random_iqp
 public :: qk_pauli_product_rotation_clear
 public :: qk_pauli_product_measurement_clear
 public :: qk_circuit_library_quantum_volume
 public :: qk_circuit_library_suzuki_trotter
 public :: qk_dag_new
 public :: qk_dag_add_quantum_register
 public :: qk_dag_add_classical_register
 public :: qk_dag_num_qubits
 public :: qk_dag_num_clbits
 public :: qk_dag_num_op_nodes
 public :: qk_dag_node_type
 public :: qk_dag_qubit_in_node
 public :: qk_dag_qubit_out_node
 public :: qk_dag_clbit_in_node
 public :: qk_dag_clbit_out_node
 public :: qk_dag_wire_node_value
 public :: qk_dag_op_node_num_qubits
 public :: qk_dag_op_node_num_clbits
 public :: qk_dag_op_node_num_params
 public :: qk_dag_op_node_qubits
 public :: qk_dag_op_node_clbits
 public :: qk_dag_apply_gate
 public :: qk_dag_apply_measure
 public :: qk_dag_apply_reset
 public :: qk_dag_apply_barrier
 public :: qk_dag_apply_unitary
 public :: qk_dag_op_node_gate_op
 public :: qk_dag_op_node_unitary
 public :: qk_dag_op_node_kind
 public :: qk_dag_successors
 public :: qk_dag_predecessors
 public :: qk_dag_neighbors_clear
 public :: qk_dag_get_instruction
 public :: qk_dag_compose
 public :: qk_dag_free
 public :: qk_dag_to_circuit
 public :: qk_dag_topological_op_nodes
 public :: qk_dag_substitute_node_with_dag
 public :: qk_dag_copy_empty_like
 public :: qk_dag_replace_block_with_unitary
 public :: qk_dag_substitute_node_with_unitary
 public :: qk_param_new_symbol
 public :: qk_param_zero
 public :: qk_param_free
 public :: qk_param_from_double
 public :: qk_param_from_complex
 public :: qk_param_copy
 public :: qk_param_str
 public :: qk_param_add
 public :: qk_param_sub
 public :: qk_param_mul
 public :: qk_param_div
 public :: qk_param_pow
 public :: qk_param_sin
 public :: qk_param_cos
 public :: qk_param_tan
 public :: qk_param_asin
 public :: qk_param_acos
 public :: qk_param_atan
 public :: qk_param_log
 public :: qk_param_exp
 public :: qk_param_abs
 public :: qk_param_sign
 public :: qk_param_neg
 public :: qk_param_conjugate
 public :: qk_param_equal
 public :: qk_param_as_real
 public :: qk_obs_zero
 public :: qk_obs_identity
 public :: qk_obs_new
 public :: qk_obs_free
 public :: qk_obs_add_term
 public :: qk_obs_term
 public :: qk_obs_num_terms
 public :: qk_obs_num_qubits
 public :: qk_obs_len
 public :: qk_obs_coeffs
 public :: qk_obs_indices
 public :: qk_obs_boundaries
 public :: qk_obs_bit_terms
 public :: qk_obs_multiply
 public :: qk_obs_multiply_inplace
 public :: qk_obs_add
 public :: qk_obs_add_inplace
 public :: qk_obs_scaled_add
 public :: qk_obs_scaled_add_inplace
 public :: qk_obs_compose
 public :: qk_obs_compose_map
 public :: qk_obs_apply_layout
 public :: qk_obs_canonicalize
 public :: qk_obs_copy
 public :: qk_obs_equal
 public :: qk_obs_str
 public :: qk_str_free
 public :: qk_obsterm_str
 public :: qk_bitterm_label
 public :: qk_neighbors_is_all_to_all
 public :: qk_neighbors_from_target
 public :: qk_neighbors_clear
 public :: qk_transpiler_pass_standalone_basis_translator
 public :: qk_transpiler_pass_standalone_commutative_cancellation
 public :: qk_transpiler_pass_standalone_consolidate_blocks
 public :: qk_transpiler_pass_standalone_convert_to_pauli_rotations
 public :: qk_transpiler_pass_standalone_elide_permutations
 public :: qk_transpiler_pass_elide_permutations
 public :: qk_transpiler_pass_standalone_check_gate_direction
 public :: qk_transpiler_pass_standalone_gate_direction
 public :: qk_transpiler_pass_check_gate_direction
 public :: qk_transpiler_pass_gate_direction
 public :: qk_transpiler_pass_standalone_inverse_cancellation
 public :: qk_transpiler_pass_standalone_litinski_transformation
 public :: qk_transpiler_standalone_optimize_1q_sequences
 public :: qk_transpiler_pass_standalone_optimize_1q_sequences
 public :: qk_transpiler_pass_optimize_1q_sequences
 public :: qk_transpiler_pass_standalone_remove_diagonal_gates_befor1RUDHG
 public :: qk_transpiler_pass_remove_diagonal_gates_before_measure
 public :: qk_transpiler_pass_standalone_remove_identity_equivalent
 public :: qk_transpiler_pass_remove_identity_equivalent
 public :: qk_sabre_layout_options_default
 public :: qk_transpiler_pass_standalone_sabre_layout
 public :: qk_transpiler_pass_standalone_split_2q_unitaries
 public :: qk_transpiler_pass_split_2q_unitaries
 public :: qk_transpiler_pass_standalone_unitary_synthesis
 public :: qk_vf2_layout_result_has_match
 public :: qk_vf2_layout_result_has_improvement
 public :: qk_vf2_layout_result_map_virtual_qubit
 public :: qk_vf2_layout_result_free
 public :: qk_vf2_layout_configuration_new
 public :: qk_vf2_layout_configuration_free
 public :: qk_vf2_layout_configuration_set_call_limit
 public :: qk_vf2_layout_configuration_set_time_limit
 public :: qk_vf2_layout_configuration_set_max_trials
 public :: qk_vf2_layout_configuration_set_shuffle_seed
 public :: qk_vf2_layout_configuration_set_score_initial
 public :: qk_transpiler_pass_standalone_vf2_layout_average
 public :: qk_transpiler_pass_standalone_vf2_layout_exact
 public :: qk_transpiler_pass_standalone_vf2_layout
 public :: qk_target_new
 public :: qk_target_num_qubits
 public :: qk_target_dt
 public :: qk_target_granularity
 public :: qk_target_min_length
 public :: qk_target_pulse_alignment
 public :: qk_target_acquire_alignment
 public :: qk_target_set_dt
 public :: qk_target_set_granularity
 public :: qk_target_set_min_length
 public :: qk_target_set_pulse_alignment
 public :: qk_target_set_acquire_alignment
 public :: qk_target_copy
 public :: qk_target_free
 public :: qk_target_entry_new
 public :: qk_target_entry_new_measure
 public :: qk_target_entry_new_reset
 public :: qk_target_entry_new_fixed
 public :: qk_target_entry_num_properties
 public :: qk_target_entry_free
 public :: qk_target_entry_add_property
 public :: qk_target_entry_set_name
 public :: qk_target_add_instruction
 public :: qk_target_update_property
 public :: qk_target_num_instructions
 public :: qk_target_instruction_supported
 public :: qk_target_op_index
 public :: qk_target_op_name
 public :: qk_target_op_num_properties
 public :: qk_target_op_qargs_index
 public :: qk_target_op_qargs
 public :: qk_target_op_props
 public :: qk_target_op_get
 public :: qk_target_op_gate
 public :: qk_target_op_clear
 public :: qk_transpile_state_new
 public :: qk_transpile_state_free
 public :: qk_transpile_state_layout
 public :: qk_transpile_state_layout_set
 public :: qk_transpiler_default_options
 public :: qk_transpile_stage_init
 public :: qk_transpile_stage_routing
 public :: qk_transpile_stage_optimization
 public :: qk_transpile_stage_translation
 public :: qk_transpile_stage_layout
 public :: qk_transpile
 public :: qk_transpile_layout_num_input_qubits
 public :: qk_transpile_layout_num_output_qubits
 public :: qk_transpile_layout_initial_layout
 public :: qk_transpile_layout_output_permutation
 public :: qk_transpile_layout_final_layout
 public :: qk_transpile_layout_generate_from_mapping
 public :: qk_transpile_layout_free

! WRAPPER DECLARATIONS
interface
function qk_api_version() &
bind(C, name="qk_api_version") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T) :: fresult
end function

function qk_circuit_new(num_qubits, num_clbits) &
bind(C, name="qk_circuit_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_INT32_T), intent(in), value :: num_clbits
type(C_PTR) :: fresult
end function

function qk_quantum_register_new(num_qubits, name) &
bind(C, name="qk_quantum_register_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
character(kind=C_CHAR), dimension(*), intent(in) :: name
type(C_PTR) :: fresult
end function

subroutine qk_quantum_register_free(reg) &
bind(C, name="qk_quantum_register_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: reg
end subroutine

subroutine qk_classical_register_free(reg) &
bind(C, name="qk_classical_register_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: reg
end subroutine

function qk_classical_register_new(num_clbits, name) &
bind(C, name="qk_classical_register_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_clbits
character(kind=C_CHAR), dimension(*), intent(in) :: name
type(C_PTR) :: fresult
end function

subroutine qk_circuit_add_quantum_register(circuit, reg) &
bind(C, name="qk_circuit_add_quantum_register")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: reg
end subroutine

subroutine qk_circuit_add_classical_register(circuit, reg) &
bind(C, name="qk_circuit_add_classical_register")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: reg
end subroutine

function qk_circuit_copy(circuit) &
bind(C, name="qk_circuit_copy") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR) :: fresult
end function

function qk_circuit_num_qubits(circuit) &
bind(C, name="qk_circuit_num_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT32_T) :: fresult
end function

function qk_circuit_num_clbits(circuit) &
bind(C, name="qk_circuit_num_clbits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT32_T) :: fresult
end function

function qk_circuit_num_param_symbols(circuit) &
bind(C, name="qk_circuit_num_param_symbols") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_SIZE_T) :: fresult
end function

subroutine qk_circuit_free(circuit) &
bind(C, name="qk_circuit_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
end subroutine

function qk_circuit_gate(circuit, gate, qubits, params) &
bind(C, name="qk_circuit_gate") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT), intent(in), value :: gate
integer(C_INT32_T), intent(in) :: qubits
real(C_DOUBLE) :: params
integer(C_INT) :: fresult
end function

function qk_circuit_parameterized_gate(circuit, gate, qubits, params) &
bind(C, name="qk_circuit_parameterized_gate") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT), intent(in), value :: gate
integer(C_INT32_T), intent(in) :: qubits
type(C_PTR), value :: params
integer(C_INT) :: fresult
end function

function qk_gate_num_qubits(gate) &
bind(C, name="qk_gate_num_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: gate
integer(C_INT32_T) :: fresult
end function

function qk_gate_num_params(gate) &
bind(C, name="qk_gate_num_params") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: gate
integer(C_INT32_T) :: fresult
end function

function qk_circuit_measure(circuit, qubit, clbit) &
bind(C, name="qk_circuit_measure") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT32_T), intent(in), value :: qubit
integer(C_INT32_T), intent(in), value :: clbit
integer(C_INT) :: fresult
end function

function qk_circuit_reset(circuit, qubit) &
bind(C, name="qk_circuit_reset") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT32_T), intent(in), value :: qubit
integer(C_INT) :: fresult
end function

function qk_circuit_barrier(circuit, qubits, num_qubits) &
bind(C, name="qk_circuit_barrier") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT32_T), intent(in) :: qubits
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_INT) :: fresult
end function

function qk_circuit_unitary(circuit, matrix, qubits, num_qubits, check_input) &
bind(C, name="qk_circuit_unitary") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: circuit
type(QkComplex64), intent(in) :: matrix
integer(C_INT32_T), intent(in) :: qubits
integer(C_INT32_T), intent(in), value :: num_qubits
logical(C_BOOL), value :: check_input
integer(C_INT) :: fresult
end function

subroutine qk_circuit_inst_unitary(circuit, index, out) &
bind(C, name="qk_circuit_inst_unitary")
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: circuit
integer(C_SIZE_T), intent(in), value :: index
type(QkComplex64) :: out
end subroutine

function qk_circuit_instruction_kind(circuit, index) &
bind(C, name="qk_circuit_instruction_kind") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_SIZE_T), intent(in), value :: index
integer(C_INT) :: fresult
end function

function qk_circuit_count_ops(circuit) &
bind(C, name="qk_circuit_count_ops") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkopcounts
type(C_PTR), value :: circuit
type(QkOpCounts) :: fresult
end function

function qk_circuit_num_instructions(circuit) &
bind(C, name="qk_circuit_num_instructions") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_SIZE_T) :: fresult
end function

subroutine qk_circuit_get_instruction(circuit, index, instruction) &
bind(C, name="qk_circuit_get_instruction")
use, intrinsic :: ISO_C_BINDING
import :: qkcircuitinstruction
type(C_PTR), value :: circuit
integer(C_SIZE_T), intent(in), value :: index
type(QkCircuitInstruction) :: instruction
end subroutine

subroutine qk_circuit_pauli_product_rotation(circuit, rotation, qubits) &
bind(C, name="qk_circuit_pauli_product_rotation")
use, intrinsic :: ISO_C_BINDING
import :: qkpauliproductrotation
type(C_PTR), value :: circuit
type(QkPauliProductRotation), intent(in) :: rotation
integer(C_INT32_T), intent(in) :: qubits
end subroutine

function qk_circuit_inst_pauli_product_rotation(circuit, index, instruction) &
bind(C, name="qk_circuit_inst_pauli_product_rotation") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkpauliproductrotation
type(C_PTR), value :: circuit
integer(C_SIZE_T), intent(in), value :: index
type(QkPauliProductRotation) :: instruction
integer(C_INT) :: fresult
end function

subroutine qk_circuit_pauli_product_measurement(circuit, measurement, qubits, clbit) &
bind(C, name="qk_circuit_pauli_product_measurement")
use, intrinsic :: ISO_C_BINDING
import :: qkpauliproductmeasurement
type(C_PTR), value :: circuit
type(QkPauliProductMeasurement), intent(in) :: measurement
integer(C_INT32_T), intent(in) :: qubits
integer(C_INT32_T), intent(in), value :: clbit
end subroutine

function qk_circuit_inst_pauli_product_measurement(circuit, index, instruction) &
bind(C, name="qk_circuit_inst_pauli_product_measurement") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkpauliproductmeasurement
type(C_PTR), value :: circuit
integer(C_SIZE_T), intent(in), value :: index
type(QkPauliProductMeasurement) :: instruction
integer(C_INT) :: fresult
end function

subroutine qk_circuit_instruction_clear(inst) &
bind(C, name="qk_circuit_instruction_clear")
use, intrinsic :: ISO_C_BINDING
import :: qkcircuitinstruction
type(QkCircuitInstruction) :: inst
end subroutine

subroutine qk_opcounts_clear(op_counts) &
bind(C, name="qk_opcounts_clear")
use, intrinsic :: ISO_C_BINDING
import :: qkopcounts
type(QkOpCounts) :: op_counts
end subroutine

function qk_circuit_delay(circuit, qubit, duration, unit) &
bind(C, name="qk_circuit_delay") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT32_T), intent(in), value :: qubit
real(C_DOUBLE), intent(in), value :: duration
integer(C_INT), intent(in), value :: unit
integer(C_INT) :: fresult
end function

function qk_circuit_draw(circuit, config) &
bind(C, name="qk_circuit_draw") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcircuitdrawerconfig
type(C_PTR), value :: circuit
type(QkCircuitDrawerConfig), intent(in) :: config
type(C_PTR) :: fresult
end function

function qk_circuit_to_dag(circuit) &
bind(C, name="qk_circuit_to_dag") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR) :: fresult
end function

function qk_circuit_copy_empty_like(circuit, vars_mode, blocks_mode) &
bind(C, name="qk_circuit_copy_empty_like") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
integer(C_INT), intent(in), value :: vars_mode
integer(C_INT), intent(in), value :: blocks_mode
type(C_PTR) :: fresult
end function

function qk_circuit_library_iqp(num_qubits, interactions, check_input) &
bind(C, name="qk_circuit_library_iqp") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_INT64_T) :: interactions
logical(C_BOOL), value :: check_input
type(C_PTR) :: fresult
end function

function qk_circuit_library_random_iqp(num_qubits, seed) &
bind(C, name="qk_circuit_library_random_iqp") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_INT64_T), intent(in), value :: seed
type(C_PTR) :: fresult
end function

subroutine qk_pauli_product_rotation_clear(inst) &
bind(C, name="qk_pauli_product_rotation_clear")
use, intrinsic :: ISO_C_BINDING
import :: qkpauliproductrotation
type(QkPauliProductRotation) :: inst
end subroutine

subroutine qk_pauli_product_measurement_clear(inst) &
bind(C, name="qk_pauli_product_measurement_clear")
use, intrinsic :: ISO_C_BINDING
import :: qkpauliproductmeasurement
type(QkPauliProductMeasurement) :: inst
end subroutine

function qk_circuit_library_quantum_volume(num_qubits, depth, seed) &
bind(C, name="qk_circuit_library_quantum_volume") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_SIZE_T), intent(in), value :: depth
integer(C_INT64_T), intent(in), value :: seed
type(C_PTR) :: fresult
end function

function qk_circuit_library_suzuki_trotter(op, order, reps, time, preserve_order, insert_barriers) &
bind(C, name="qk_circuit_library_suzuki_trotter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: op
integer(C_INT32_T), intent(in), value :: order
integer(C_INT32_T), intent(in), value :: reps
real(C_DOUBLE), intent(in), value :: time
logical(C_BOOL), value :: preserve_order
logical(C_BOOL), value :: insert_barriers
type(C_PTR) :: fresult
end function

function qk_dag_new() &
bind(C, name="qk_dag_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

subroutine qk_dag_add_quantum_register(dag, reg) &
bind(C, name="qk_dag_add_quantum_register")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR), value :: reg
end subroutine

subroutine qk_dag_add_classical_register(dag, reg) &
bind(C, name="qk_dag_add_classical_register")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR), value :: reg
end subroutine

function qk_dag_num_qubits(dag) &
bind(C, name="qk_dag_num_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T) :: fresult
end function

function qk_dag_num_clbits(dag) &
bind(C, name="qk_dag_num_clbits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T) :: fresult
end function

function qk_dag_num_op_nodes(dag) &
bind(C, name="qk_dag_num_op_nodes") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_SIZE_T) :: fresult
end function

function qk_dag_node_type(dag, node) &
bind(C, name="qk_dag_node_type") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
integer(C_INT) :: fresult
end function

function qk_dag_qubit_in_node(dag, qubit) &
bind(C, name="qk_dag_qubit_in_node") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: qubit
integer(C_INT32_T) :: fresult
end function

function qk_dag_qubit_out_node(dag, qubit) &
bind(C, name="qk_dag_qubit_out_node") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: qubit
integer(C_INT32_T) :: fresult
end function

function qk_dag_clbit_in_node(dag, clbit) &
bind(C, name="qk_dag_clbit_in_node") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: clbit
integer(C_INT32_T) :: fresult
end function

function qk_dag_clbit_out_node(dag, clbit) &
bind(C, name="qk_dag_clbit_out_node") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: clbit
integer(C_INT32_T) :: fresult
end function

function qk_dag_wire_node_value(dag, node) &
bind(C, name="qk_dag_wire_node_value") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
integer(C_INT32_T) :: fresult
end function

function qk_dag_op_node_num_qubits(dag, node) &
bind(C, name="qk_dag_op_node_num_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
integer(C_INT32_T) :: fresult
end function

function qk_dag_op_node_num_clbits(dag, node) &
bind(C, name="qk_dag_op_node_num_clbits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
integer(C_INT32_T) :: fresult
end function

function qk_dag_op_node_num_params(dag, node) &
bind(C, name="qk_dag_op_node_num_params") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
integer(C_INT32_T) :: fresult
end function

function qk_dag_op_node_qubits(dag, node) &
bind(C, name="qk_dag_op_node_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
type(C_PTR) :: fresult
end function

function qk_dag_op_node_clbits(dag, node) &
bind(C, name="qk_dag_op_node_clbits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
type(C_PTR) :: fresult
end function

function qk_dag_apply_gate(dag, gate, qubits, params, front) &
bind(C, name="qk_dag_apply_gate") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT), intent(in), value :: gate
integer(C_INT32_T), intent(in) :: qubits
real(C_DOUBLE) :: params
logical(C_BOOL), value :: front
integer(C_INT32_T) :: fresult
end function

function qk_dag_apply_measure(dag, qubit, clbit, front) &
bind(C, name="qk_dag_apply_measure") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: qubit
integer(C_INT32_T), intent(in), value :: clbit
logical(C_BOOL), value :: front
integer(C_INT32_T) :: fresult
end function

function qk_dag_apply_reset(dag, qubit, front) &
bind(C, name="qk_dag_apply_reset") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: qubit
logical(C_BOOL), value :: front
integer(C_INT32_T) :: fresult
end function

function qk_dag_apply_barrier(dag, qubits, num_qubits, front) &
bind(C, name="qk_dag_apply_barrier") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in) :: qubits
integer(C_INT32_T), intent(in), value :: num_qubits
logical(C_BOOL), value :: front
integer(C_INT32_T) :: fresult
end function

function qk_dag_apply_unitary(dag, matrix, qubits, num_qubits, front) &
bind(C, name="qk_dag_apply_unitary") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: dag
type(QkComplex64), intent(in) :: matrix
integer(C_INT32_T), intent(in) :: qubits
integer(C_INT32_T), intent(in), value :: num_qubits
logical(C_BOOL), value :: front
integer(C_INT32_T) :: fresult
end function

function qk_dag_op_node_gate_op(dag, node, out_params) &
bind(C, name="qk_dag_op_node_gate_op") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
real(C_DOUBLE) :: out_params
integer(C_INT) :: fresult
end function

subroutine qk_dag_op_node_unitary(dag, node, out) &
bind(C, name="qk_dag_op_node_unitary")
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
type(QkComplex64) :: out
end subroutine

function qk_dag_op_node_kind(dag, node) &
bind(C, name="qk_dag_op_node_kind") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
integer(C_INT) :: fresult
end function

function qk_dag_successors(dag, node) &
bind(C, name="qk_dag_successors") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkdagneighbors
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
type(QkDagNeighbors) :: fresult
end function

function qk_dag_predecessors(dag, node) &
bind(C, name="qk_dag_predecessors") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkdagneighbors
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
type(QkDagNeighbors) :: fresult
end function

subroutine qk_dag_neighbors_clear(neighbors) &
bind(C, name="qk_dag_neighbors_clear")
use, intrinsic :: ISO_C_BINDING
import :: qkdagneighbors
type(QkDagNeighbors) :: neighbors
end subroutine

subroutine qk_dag_get_instruction(dag, index, instruction) &
bind(C, name="qk_dag_get_instruction")
use, intrinsic :: ISO_C_BINDING
import :: qkcircuitinstruction
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: index
type(QkCircuitInstruction) :: instruction
end subroutine

function qk_dag_compose(dag, other, qubits, clbits) &
bind(C, name="qk_dag_compose") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR), value :: other
integer(C_INT32_T), intent(in) :: qubits
integer(C_INT32_T), intent(in) :: clbits
integer(C_INT) :: fresult
end function

subroutine qk_dag_free(dag) &
bind(C, name="qk_dag_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
end subroutine

function qk_dag_to_circuit(dag) &
bind(C, name="qk_dag_to_circuit") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR) :: fresult
end function

subroutine qk_dag_topological_op_nodes(dag, out_order) &
bind(C, name="qk_dag_topological_op_nodes")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T) :: out_order
end subroutine

subroutine qk_dag_substitute_node_with_dag(dag, node, replacement) &
bind(C, name="qk_dag_substitute_node_with_dag")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
type(C_PTR), value :: replacement
end subroutine

function qk_dag_copy_empty_like(dag, vars_mode, blocks_mode) &
bind(C, name="qk_dag_copy_empty_like") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
integer(C_INT), intent(in), value :: vars_mode
integer(C_INT), intent(in), value :: blocks_mode
type(C_PTR) :: fresult
end function

function qk_dag_replace_block_with_unitary(dag, num_block_ids, block_ids, matrix, num_qubits, qubits, cycle_check) &
bind(C, name="qk_dag_replace_block_with_unitary") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: num_block_ids
integer(C_INT32_T), intent(in) :: block_ids
type(QkComplex64), intent(in) :: matrix
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_INT32_T), intent(in) :: qubits
logical(C_BOOL), value :: cycle_check
integer(C_INT32_T) :: fresult
end function

subroutine qk_dag_substitute_node_with_unitary(dag, node, matrix, num_qubits) &
bind(C, name="qk_dag_substitute_node_with_unitary")
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: dag
integer(C_INT32_T), intent(in), value :: node
type(QkComplex64), intent(in) :: matrix
integer(C_INT32_T), intent(in), value :: num_qubits
end subroutine

function qk_param_new_symbol(name) &
bind(C, name="qk_param_new_symbol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR), dimension(*), intent(in) :: name
type(C_PTR) :: fresult
end function

function qk_param_zero() &
bind(C, name="qk_param_zero") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

subroutine qk_param_free(param) &
bind(C, name="qk_param_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: param
end subroutine

function qk_param_from_double(value) &
bind(C, name="qk_param_from_double") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in), value :: value
type(C_PTR) :: fresult
end function

function qk_param_from_complex(value) &
bind(C, name="qk_param_from_complex") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(QkComplex64), intent(in), value :: value
type(C_PTR) :: fresult
end function

function qk_param_copy(param) &
bind(C, name="qk_param_copy") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: param
type(C_PTR) :: fresult
end function

function qk_param_str(param) &
bind(C, name="qk_param_str") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: param
type(C_PTR) :: fresult
end function

function qk_param_add(out, lhs, rhs) &
bind(C, name="qk_param_add") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: lhs
type(C_PTR), value :: rhs
integer(C_INT) :: fresult
end function

function qk_param_sub(out, lhs, rhs) &
bind(C, name="qk_param_sub") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: lhs
type(C_PTR), value :: rhs
integer(C_INT) :: fresult
end function

function qk_param_mul(out, lhs, rhs) &
bind(C, name="qk_param_mul") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: lhs
type(C_PTR), value :: rhs
integer(C_INT) :: fresult
end function

function qk_param_div(out, num, den) &
bind(C, name="qk_param_div") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: num
type(C_PTR), value :: den
integer(C_INT) :: fresult
end function

function qk_param_pow(out, base, pow) &
bind(C, name="qk_param_pow") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: base
type(C_PTR), value :: pow
integer(C_INT) :: fresult
end function

function qk_param_sin(out, src) &
bind(C, name="qk_param_sin") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_cos(out, src) &
bind(C, name="qk_param_cos") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_tan(out, src) &
bind(C, name="qk_param_tan") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_asin(out, src) &
bind(C, name="qk_param_asin") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_acos(out, src) &
bind(C, name="qk_param_acos") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_atan(out, src) &
bind(C, name="qk_param_atan") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_log(out, src) &
bind(C, name="qk_param_log") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_exp(out, src) &
bind(C, name="qk_param_exp") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_abs(out, src) &
bind(C, name="qk_param_abs") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_sign(out, src) &
bind(C, name="qk_param_sign") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_neg(out, src) &
bind(C, name="qk_param_neg") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_conjugate(out, src) &
bind(C, name="qk_param_conjugate") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: out
type(C_PTR), value :: src
integer(C_INT) :: fresult
end function

function qk_param_equal(lhs, rhs) &
bind(C, name="qk_param_equal") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: lhs
type(C_PTR), value :: rhs
logical(C_BOOL) :: fresult
end function

function qk_param_as_real(param) &
bind(C, name="qk_param_as_real") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: param
real(C_DOUBLE) :: fresult
end function

function qk_obs_zero(num_qubits) &
bind(C, name="qk_obs_zero") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
type(C_PTR) :: fresult
end function

function qk_obs_identity(num_qubits) &
bind(C, name="qk_obs_identity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
type(C_PTR) :: fresult
end function

function qk_obs_new(num_qubits, num_terms, num_bits, coeffs, bit_terms, indices, boundaries) &
bind(C, name="qk_obs_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_INT64_T), intent(in), value :: num_terms
integer(C_INT64_T), intent(in), value :: num_bits
type(QkComplex64) :: coeffs
integer(C_INT) :: bit_terms
integer(C_INT32_T) :: indices
integer(C_SIZE_T) :: boundaries
type(C_PTR) :: fresult
end function

subroutine qk_obs_free(obs) &
bind(C, name="qk_obs_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
end subroutine

function qk_obs_add_term(obs, cterm) &
bind(C, name="qk_obs_add_term") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkobsterm
type(C_PTR), value :: obs
type(QkObsTerm), intent(in) :: cterm
integer(C_INT) :: fresult
end function

function qk_obs_term(obs, index, out) &
bind(C, name="qk_obs_term") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkobsterm
type(C_PTR), value :: obs
integer(C_INT64_T), intent(in), value :: index
type(QkObsTerm) :: out
integer(C_INT) :: fresult
end function

function qk_obs_num_terms(obs) &
bind(C, name="qk_obs_num_terms") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
integer(C_SIZE_T) :: fresult
end function

function qk_obs_num_qubits(obs) &
bind(C, name="qk_obs_num_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
integer(C_INT32_T) :: fresult
end function

function qk_obs_len(obs) &
bind(C, name="qk_obs_len") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
integer(C_SIZE_T) :: fresult
end function

function qk_obs_coeffs(obs) &
bind(C, name="qk_obs_coeffs") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
type(C_PTR) :: fresult
end function

function qk_obs_indices(obs) &
bind(C, name="qk_obs_indices") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
type(C_PTR) :: fresult
end function

function qk_obs_boundaries(obs) &
bind(C, name="qk_obs_boundaries") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
type(C_PTR) :: fresult
end function

function qk_obs_bit_terms(obs) &
bind(C, name="qk_obs_bit_terms") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
type(C_PTR) :: fresult
end function

function qk_obs_multiply(obs, coeff) &
bind(C, name="qk_obs_multiply") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: obs
type(QkComplex64), intent(in) :: coeff
type(C_PTR) :: fresult
end function

subroutine qk_obs_multiply_inplace(obs, coeff) &
bind(C, name="qk_obs_multiply_inplace")
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: obs
type(QkComplex64), intent(in) :: coeff
end subroutine

function qk_obs_add(left, right) &
bind(C, name="qk_obs_add") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: left
type(C_PTR), value :: right
type(C_PTR) :: fresult
end function

subroutine qk_obs_add_inplace(left, right) &
bind(C, name="qk_obs_add_inplace")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: left
type(C_PTR), value :: right
end subroutine

function qk_obs_scaled_add(left, right, factor) &
bind(C, name="qk_obs_scaled_add") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: left
type(C_PTR), value :: right
type(QkComplex64), intent(in) :: factor
type(C_PTR) :: fresult
end function

subroutine qk_obs_scaled_add_inplace(left, right, factor) &
bind(C, name="qk_obs_scaled_add_inplace")
use, intrinsic :: ISO_C_BINDING
import :: qkcomplex64
type(C_PTR), value :: left
type(C_PTR), value :: right
type(QkComplex64), intent(in) :: factor
end subroutine

function qk_obs_compose(first, second) &
bind(C, name="qk_obs_compose") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: first
type(C_PTR), value :: second
type(C_PTR) :: fresult
end function

function qk_obs_compose_map(first, second, qargs) &
bind(C, name="qk_obs_compose_map") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: first
type(C_PTR), value :: second
integer(C_INT32_T), intent(in) :: qargs
type(C_PTR) :: fresult
end function

function qk_obs_apply_layout(obs, layout, num_qubits) &
bind(C, name="qk_obs_apply_layout") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
integer(C_INT32_T), intent(in) :: layout
integer(C_INT32_T), intent(in), value :: num_qubits
integer(C_INT) :: fresult
end function

function qk_obs_canonicalize(obs, tol) &
bind(C, name="qk_obs_canonicalize") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
real(C_DOUBLE), intent(in), value :: tol
type(C_PTR) :: fresult
end function

function qk_obs_copy(obs) &
bind(C, name="qk_obs_copy") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
type(C_PTR) :: fresult
end function

function qk_obs_equal(obs, other) &
bind(C, name="qk_obs_equal") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
type(C_PTR), value :: other
logical(C_BOOL) :: fresult
end function

function qk_obs_str(obs) &
bind(C, name="qk_obs_str") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: obs
type(C_PTR) :: fresult
end function

subroutine qk_str_free(string) &
bind(C, name="qk_str_free")
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=*) :: string
end subroutine

function qk_obsterm_str(term) &
bind(C, name="qk_obsterm_str") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkobsterm
type(QkObsTerm), intent(in) :: term
type(C_PTR) :: fresult
end function

function qk_bitterm_label(bit_term) &
bind(C, name="qk_bitterm_label") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: bit_term
integer(C_INT8_T) :: fresult
end function

function qk_neighbors_is_all_to_all(neighbors) &
bind(C, name="qk_neighbors_is_all_to_all") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkneighbors
type(QkNeighbors), intent(in) :: neighbors
logical(C_BOOL) :: fresult
end function

function qk_neighbors_from_target(target, neighbors) &
bind(C, name="qk_neighbors_from_target") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qkneighbors
type(C_PTR), value :: target
type(QkNeighbors) :: neighbors
logical(C_BOOL) :: fresult
end function

subroutine qk_neighbors_clear(neighbors) &
bind(C, name="qk_neighbors_clear")
use, intrinsic :: ISO_C_BINDING
import :: qkneighbors
type(QkNeighbors) :: neighbors
end subroutine

subroutine qk_transpiler_pass_standalone_basis_translator(circuit, target, min_qubits) &
bind(C, name="qk_transpiler_pass_standalone_basis_translator")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: min_qubits
end subroutine

function qk_transpiler_pass_standalone_commutative_cancellation(circuit, target, approximation_degree) &
bind(C, name="qk_transpiler_pass_standalone_commutative_cancellation") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
real(C_DOUBLE), intent(in), value :: approximation_degree
integer(C_INT) :: fresult
end function

subroutine qk_transpiler_pass_standalone_consolidate_blocks(circuit, target, approximation_degree, force_consolidate) &
bind(C, name="qk_transpiler_pass_standalone_consolidate_blocks")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
real(C_DOUBLE), intent(in), value :: approximation_degree
logical(C_BOOL), value :: force_consolidate
end subroutine

subroutine qk_transpiler_pass_standalone_convert_to_pauli_rotations(circuit) &
bind(C, name="qk_transpiler_pass_standalone_convert_to_pauli_rotations")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
end subroutine

function qk_transpiler_pass_standalone_elide_permutations(circuit) &
bind(C, name="qk_transpiler_pass_standalone_elide_permutations") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR) :: fresult
end function

function qk_transpiler_pass_elide_permutations(dag) &
bind(C, name="qk_transpiler_pass_elide_permutations") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR) :: fresult
end function

function qk_transpiler_pass_standalone_check_gate_direction(circuit, target) &
bind(C, name="qk_transpiler_pass_standalone_check_gate_direction") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
logical(C_BOOL) :: fresult
end function

subroutine qk_transpiler_pass_standalone_gate_direction(circuit, target) &
bind(C, name="qk_transpiler_pass_standalone_gate_direction")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
end subroutine

function qk_transpiler_pass_check_gate_direction(dag, target) &
bind(C, name="qk_transpiler_pass_check_gate_direction") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR), value :: target
logical(C_BOOL) :: fresult
end function

subroutine qk_transpiler_pass_gate_direction(dag, target) &
bind(C, name="qk_transpiler_pass_gate_direction")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR), value :: target
end subroutine

subroutine qk_transpiler_pass_standalone_inverse_cancellation(circuit) &
bind(C, name="qk_transpiler_pass_standalone_inverse_cancellation")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
end subroutine

subroutine qk_transpiler_pass_standalone_litinski_transformation(circuit, fix_clifford) &
bind(C, name="qk_transpiler_pass_standalone_litinski_transformation")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
logical(C_BOOL), value :: fix_clifford
end subroutine

subroutine qk_transpiler_standalone_optimize_1q_sequences(circuit, target) &
bind(C, name="qk_transpiler_standalone_optimize_1q_sequences")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
end subroutine

subroutine qk_transpiler_pass_standalone_optimize_1q_sequences(circuit, target) &
bind(C, name="qk_transpiler_pass_standalone_optimize_1q_sequences")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
end subroutine

subroutine qk_transpiler_pass_optimize_1q_sequences(dag, target) &
bind(C, name="qk_transpiler_pass_optimize_1q_sequences")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR), value :: target
end subroutine

subroutine qk_transpiler_pass_standalone_remove_diagonal_gates_befor1RUDHG(circuit) &
bind(C, name="qk_transpiler_pass_standalone_remove_diagonal_gates_before_measure")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
end subroutine

subroutine qk_transpiler_pass_remove_diagonal_gates_before_measure(dag) &
bind(C, name="qk_transpiler_pass_remove_diagonal_gates_before_measure")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
end subroutine

subroutine qk_transpiler_pass_standalone_remove_identity_equivalent(circuit, target, approximation_degree) &
bind(C, name="qk_transpiler_pass_standalone_remove_identity_equivalent")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
real(C_DOUBLE), intent(in), value :: approximation_degree
end subroutine

subroutine qk_transpiler_pass_remove_identity_equivalent(dag, target, approximation_degree) &
bind(C, name="qk_transpiler_pass_remove_identity_equivalent")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
type(C_PTR), value :: target
real(C_DOUBLE), intent(in), value :: approximation_degree
end subroutine

function qk_sabre_layout_options_default() &
bind(C, name="qk_sabre_layout_options_default") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qksabrelayoutoptions
type(QkSabreLayoutOptions) :: fresult
end function

function qk_transpiler_pass_standalone_sabre_layout(circuit, target, options) &
bind(C, name="qk_transpiler_pass_standalone_sabre_layout") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qksabrelayoutoptions
type(C_PTR), value :: circuit
type(C_PTR), value :: target
type(QkSabreLayoutOptions), intent(in) :: options
type(C_PTR) :: fresult
end function

function qk_transpiler_pass_standalone_split_2q_unitaries(circuit, requested_fidelity, split_swaps) &
bind(C, name="qk_transpiler_pass_standalone_split_2q_unitaries") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
real(C_DOUBLE), intent(in), value :: requested_fidelity
logical(C_BOOL), value :: split_swaps
type(C_PTR) :: fresult
end function

function qk_transpiler_pass_split_2q_unitaries(dag, requested_fidelity, split_swaps) &
bind(C, name="qk_transpiler_pass_split_2q_unitaries") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: dag
real(C_DOUBLE), intent(in), value :: requested_fidelity
logical(C_BOOL), value :: split_swaps
type(C_PTR) :: fresult
end function

subroutine qk_transpiler_pass_standalone_unitary_synthesis(circuit, target, min_qubits, approximation_degree) &
bind(C, name="qk_transpiler_pass_standalone_unitary_synthesis")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: min_qubits
real(C_DOUBLE), intent(in), value :: approximation_degree
end subroutine

function qk_vf2_layout_result_has_match(layout) &
bind(C, name="qk_vf2_layout_result_has_match") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
logical(C_BOOL) :: fresult
end function

function qk_vf2_layout_result_has_improvement(layout) &
bind(C, name="qk_vf2_layout_result_has_improvement") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
logical(C_BOOL) :: fresult
end function

function qk_vf2_layout_result_map_virtual_qubit(layout, qubit) &
bind(C, name="qk_vf2_layout_result_map_virtual_qubit") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
integer(C_INT32_T), intent(in), value :: qubit
integer(C_INT32_T) :: fresult
end function

subroutine qk_vf2_layout_result_free(layout) &
bind(C, name="qk_vf2_layout_result_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
end subroutine

function qk_vf2_layout_configuration_new() &
bind(C, name="qk_vf2_layout_configuration_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

subroutine qk_vf2_layout_configuration_free(config) &
bind(C, name="qk_vf2_layout_configuration_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: config
end subroutine

subroutine qk_vf2_layout_configuration_set_call_limit(config, before, after) &
bind(C, name="qk_vf2_layout_configuration_set_call_limit")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: config
integer(C_INT64_T), intent(in), value :: before
integer(C_INT64_T), intent(in), value :: after
end subroutine

subroutine qk_vf2_layout_configuration_set_time_limit(config, limit) &
bind(C, name="qk_vf2_layout_configuration_set_time_limit")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: config
real(C_DOUBLE), intent(in), value :: limit
end subroutine

subroutine qk_vf2_layout_configuration_set_max_trials(config, limit) &
bind(C, name="qk_vf2_layout_configuration_set_max_trials")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: config
integer(C_INT64_T), intent(in), value :: limit
end subroutine

subroutine qk_vf2_layout_configuration_set_shuffle_seed(config, seed) &
bind(C, name="qk_vf2_layout_configuration_set_shuffle_seed")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: config
integer(C_INT64_T), intent(in), value :: seed
end subroutine

subroutine qk_vf2_layout_configuration_set_score_initial(config, score_initial) &
bind(C, name="qk_vf2_layout_configuration_set_score_initial")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: config
logical(C_BOOL), value :: score_initial
end subroutine

function qk_transpiler_pass_standalone_vf2_layout_average(circuit, target, config, strict_direction) &
bind(C, name="qk_transpiler_pass_standalone_vf2_layout_average") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
type(C_PTR), value :: config
logical(C_BOOL), value :: strict_direction
type(C_PTR) :: fresult
end function

function qk_transpiler_pass_standalone_vf2_layout_exact(circuit, target, config) &
bind(C, name="qk_transpiler_pass_standalone_vf2_layout_exact") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
type(C_PTR), value :: config
type(C_PTR) :: fresult
end function

function qk_transpiler_pass_standalone_vf2_layout(circuit, target, strict_direction, call_limit, time_limit, max_trials) &
bind(C, name="qk_transpiler_pass_standalone_vf2_layout") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: circuit
type(C_PTR), value :: target
logical(C_BOOL), value :: strict_direction
integer(C_INT64_T), intent(in), value :: call_limit
real(C_DOUBLE), intent(in), value :: time_limit
integer(C_INT64_T), intent(in), value :: max_trials
type(C_PTR) :: fresult
end function

function qk_target_new(num_qubits) &
bind(C, name="qk_target_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), intent(in), value :: num_qubits
type(C_PTR) :: fresult
end function

function qk_target_num_qubits(target) &
bind(C, name="qk_target_num_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T) :: fresult
end function

function qk_target_dt(target) &
bind(C, name="qk_target_dt") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
real(C_DOUBLE) :: fresult
end function

function qk_target_granularity(target) &
bind(C, name="qk_target_granularity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T) :: fresult
end function

function qk_target_min_length(target) &
bind(C, name="qk_target_min_length") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T) :: fresult
end function

function qk_target_pulse_alignment(target) &
bind(C, name="qk_target_pulse_alignment") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T) :: fresult
end function

function qk_target_acquire_alignment(target) &
bind(C, name="qk_target_acquire_alignment") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T) :: fresult
end function

function qk_target_set_dt(target, dt) &
bind(C, name="qk_target_set_dt") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
real(C_DOUBLE), intent(in), value :: dt
integer(C_INT) :: fresult
end function

function qk_target_set_granularity(target, granularity) &
bind(C, name="qk_target_set_granularity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T), intent(in), value :: granularity
integer(C_INT) :: fresult
end function

function qk_target_set_min_length(target, min_length) &
bind(C, name="qk_target_set_min_length") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T), intent(in), value :: min_length
integer(C_INT) :: fresult
end function

function qk_target_set_pulse_alignment(target, pulse_alignment) &
bind(C, name="qk_target_set_pulse_alignment") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T), intent(in), value :: pulse_alignment
integer(C_INT) :: fresult
end function

function qk_target_set_acquire_alignment(target, acquire_alignment) &
bind(C, name="qk_target_set_acquire_alignment") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT32_T), intent(in), value :: acquire_alignment
integer(C_INT) :: fresult
end function

function qk_target_copy(target) &
bind(C, name="qk_target_copy") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
type(C_PTR) :: fresult
end function

subroutine qk_target_free(target) &
bind(C, name="qk_target_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
end subroutine

function qk_target_entry_new(operation) &
bind(C, name="qk_target_entry_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: operation
type(C_PTR) :: fresult
end function

function qk_target_entry_new_measure() &
bind(C, name="qk_target_entry_new_measure") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

function qk_target_entry_new_reset() &
bind(C, name="qk_target_entry_new_reset") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

function qk_target_entry_new_fixed(operation, params, name) &
bind(C, name="qk_target_entry_new_fixed") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: operation
real(C_DOUBLE) :: params
character(kind=C_CHAR), dimension(*), intent(in) :: name
type(C_PTR) :: fresult
end function

function qk_target_entry_num_properties(entry) &
bind(C, name="qk_target_entry_num_properties") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: entry
integer(C_SIZE_T) :: fresult
end function

subroutine qk_target_entry_free(entry) &
bind(C, name="qk_target_entry_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: entry
end subroutine

function qk_target_entry_add_property(entry, qargs, num_qubits, duration, error) &
bind(C, name="qk_target_entry_add_property") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: entry
integer(C_INT32_T) :: qargs
integer(C_INT32_T), intent(in), value :: num_qubits
real(C_DOUBLE), intent(in), value :: duration
real(C_DOUBLE), intent(in), value :: error
integer(C_INT) :: fresult
end function

function qk_target_entry_set_name(entry, name) &
bind(C, name="qk_target_entry_set_name") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: entry
character(kind=C_CHAR), dimension(*), intent(in) :: name
integer(C_INT) :: fresult
end function

function qk_target_add_instruction(target, target_entry) &
bind(C, name="qk_target_add_instruction") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
type(C_PTR), value :: target_entry
integer(C_INT) :: fresult
end function

function qk_target_update_property(target, instruction, qargs, num_qubits, duration, error) &
bind(C, name="qk_target_update_property") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_INT), intent(in), value :: instruction
integer(C_INT32_T) :: qargs
integer(C_INT32_T), intent(in), value :: num_qubits
real(C_DOUBLE), intent(in), value :: duration
real(C_DOUBLE), intent(in), value :: error
integer(C_INT) :: fresult
end function

function qk_target_num_instructions(target) &
bind(C, name="qk_target_num_instructions") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_SIZE_T) :: fresult
end function

function qk_target_instruction_supported(target, operation_name, qargs, params) &
bind(C, name="qk_target_instruction_supported") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
character(kind=C_CHAR), dimension(*), intent(in) :: operation_name
integer(C_INT32_T), intent(in) :: qargs
type(C_PTR), value :: params
logical(C_BOOL) :: fresult
end function

function qk_target_op_index(target, name) &
bind(C, name="qk_target_op_index") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
character(kind=C_CHAR), dimension(*), intent(in) :: name
integer(C_SIZE_T) :: fresult
end function

function qk_target_op_name(target, index) &
bind(C, name="qk_target_op_name") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: index
type(C_PTR) :: fresult
end function

function qk_target_op_num_properties(target, index) &
bind(C, name="qk_target_op_num_properties") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: index
integer(C_SIZE_T) :: fresult
end function

function qk_target_op_qargs_index(target, op_idx, qargs) &
bind(C, name="qk_target_op_qargs_index") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: op_idx
integer(C_INT32_T), intent(in) :: qargs
integer(C_SIZE_T) :: fresult
end function

subroutine qk_target_op_qargs(target, op_idx, qarg_idx, qargs_out, qargs_len) &
bind(C, name="qk_target_op_qargs")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: op_idx
integer(C_SIZE_T), intent(in), value :: qarg_idx
type(C_PTR), value :: qargs_out
integer(C_INT32_T) :: qargs_len
end subroutine

subroutine qk_target_op_props(target, op_idx, qarg_idx, inst_props) &
bind(C, name="qk_target_op_props")
use, intrinsic :: ISO_C_BINDING
import :: qkinstructionproperties
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: op_idx
integer(C_SIZE_T), intent(in), value :: qarg_idx
type(QkInstructionProperties) :: inst_props
end subroutine

subroutine qk_target_op_get(target, index, out_op) &
bind(C, name="qk_target_op_get")
use, intrinsic :: ISO_C_BINDING
import :: qktargetop
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: index
type(QkTargetOp) :: out_op
end subroutine

function qk_target_op_gate(target, index) &
bind(C, name="qk_target_op_gate") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: target
integer(C_SIZE_T), intent(in), value :: index
integer(C_INT) :: fresult
end function

subroutine qk_target_op_clear(op) &
bind(C, name="qk_target_op_clear")
use, intrinsic :: ISO_C_BINDING
import :: qktargetop
type(QkTargetOp) :: op
end subroutine

subroutine qk_transpile_state_new(state) &
bind(C, name="qk_transpile_state_new")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: state
end subroutine

subroutine qk_transpile_state_free(state) &
bind(C, name="qk_transpile_state_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: state
end subroutine

function qk_transpile_state_layout(state) &
bind(C, name="qk_transpile_state_layout") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: state
type(C_PTR) :: fresult
end function

subroutine qk_transpile_state_layout_set(state, layout) &
bind(C, name="qk_transpile_state_layout_set")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: state
type(C_PTR), value :: layout
end subroutine

function qk_transpiler_default_options() &
bind(C, name="qk_transpiler_default_options") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qktranspileoptions
type(QkTranspileOptions) :: fresult
end function

function qk_transpile_stage_init(dag, target, options, state, error) &
bind(C, name="qk_transpile_stage_init") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qktranspileoptions
type(C_PTR), value :: dag
type(C_PTR), value :: target
type(QkTranspileOptions), intent(in) :: options
type(C_PTR), value :: state
type(C_PTR), value :: error
integer(C_INT) :: fresult
end function

function qk_transpile_stage_routing(dag, target, options, state, error) &
bind(C, name="qk_transpile_stage_routing") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qktranspileoptions
type(C_PTR), value :: dag
type(C_PTR), value :: target
type(QkTranspileOptions), intent(in) :: options
type(C_PTR), value :: state
type(C_PTR), value :: error
integer(C_INT) :: fresult
end function

function qk_transpile_stage_optimization(dag, target, options, error, state) &
bind(C, name="qk_transpile_stage_optimization") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qktranspileoptions
type(C_PTR), value :: dag
type(C_PTR), value :: target
type(QkTranspileOptions), intent(in) :: options
type(C_PTR), value :: error
type(C_PTR), value :: state
integer(C_INT) :: fresult
end function

function qk_transpile_stage_translation(dag, target, options, error) &
bind(C, name="qk_transpile_stage_translation") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qktranspileoptions
type(C_PTR), value :: dag
type(C_PTR), value :: target
type(QkTranspileOptions), intent(in) :: options
type(C_PTR), value :: error
integer(C_INT) :: fresult
end function

function qk_transpile_stage_layout(dag, target, options, state, error) &
bind(C, name="qk_transpile_stage_layout") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qktranspileoptions
type(C_PTR), value :: dag
type(C_PTR), value :: target
type(QkTranspileOptions), intent(in) :: options
type(C_PTR), value :: state
type(C_PTR), value :: error
integer(C_INT) :: fresult
end function

function qk_transpile(qc, target, options, result, error) &
bind(C, name="qk_transpile") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: qktranspileoptions
import :: qktranspileresult
type(C_PTR), value :: qc
type(C_PTR), value :: target
type(QkTranspileOptions), intent(in) :: options
type(QkTranspileResult) :: result
type(C_PTR), value :: error
integer(C_INT) :: fresult
end function

function qk_transpile_layout_num_input_qubits(layout) &
bind(C, name="qk_transpile_layout_num_input_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
integer(C_INT32_T) :: fresult
end function

function qk_transpile_layout_num_output_qubits(layout) &
bind(C, name="qk_transpile_layout_num_output_qubits") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
integer(C_INT32_T) :: fresult
end function

function qk_transpile_layout_initial_layout(layout, filter_ancillas, initial_layout) &
bind(C, name="qk_transpile_layout_initial_layout") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
logical(C_BOOL), value :: filter_ancillas
integer(C_INT32_T) :: initial_layout
logical(C_BOOL) :: fresult
end function

function qk_transpile_layout_output_permutation(layout, output_permutation) &
bind(C, name="qk_transpile_layout_output_permutation") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
integer(C_INT32_T) :: output_permutation
logical(C_BOOL) :: fresult
end function

subroutine qk_transpile_layout_final_layout(layout, filter_ancillas, final_layout) &
bind(C, name="qk_transpile_layout_final_layout")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
logical(C_BOOL), value :: filter_ancillas
integer(C_INT32_T) :: final_layout
end subroutine

function qk_transpile_layout_generate_from_mapping(original_dag, target, qubit_mapping) &
bind(C, name="qk_transpile_layout_generate_from_mapping") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: original_dag
type(C_PTR), value :: target
integer(C_INT32_T), intent(in) :: qubit_mapping
type(C_PTR) :: fresult
end function

subroutine qk_transpile_layout_free(layout) &
bind(C, name="qk_transpile_layout_free")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: layout
end subroutine

end interface


end module
